
/*
						I. Phần 1. TẠO CSDL VÀ NHẬP LIỆU
*/
CREATE DATABASE QuanLyCuaHangThuCung
GO
USE QuanLyCuaHangThuCung

/*
USE master
DROP DATABASE QuanLyCuaHangThuCung
*/


/*
--------------------------------------TẠO BẢNG--------------------------------------
------------------------------------------------------------------------------------
1. NHANVIEN			-	Nhân viên
2. TAIKHOAN			-	Tài khoản
3. LOAI				-	Loài
4. THUCUNG			-	Thú cưng
5. HOADON			-	Hóa đơn
6. CHITIETHOADON	-	Chi tiết hóa đơn
7. KHUYENMAI		-	Khuyến mãi
*/


CREATE TABLE NHANVIEN(
	MANV VARCHAR(5) NOT NULL,
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(3),
	NGAYSINH DATE,
	DIACHI NVARCHAR(200),
	SDT VARCHAR(12),
	CHUCVU VARCHAR(10),
	LUONG INT,
	CMND VARCHAR(10),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)

CREATE TABLE TAIKHOAN(	
	MANV VARCHAR(5),
	TENTK VARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TENTK)
)

-- Cảm thấy bảng LOAI và THUCUNG không ổn
CREATE TABLE LOAI( -- Không rõ LOAI ở đây chính xác là gì
	MALOAI VARCHAR(3) NOT NULL,
	TENLOAI NVARCHAR(50),
	CONSTRAINT PK_LOAI PRIMARY KEY (MALOAI)
)

CREATE TABLE CHITIETLOAI(
	MAGIONG VARCHAR(5),
	MALOAI VARCHAR(3),
	TENGIONG NVARCHAR(20),
	MOTA NVARCHAR(500)
	CONSTRAINT PK_CHITIETLOAI PRIMARY KEY (MAGIONG)
)

CREATE TABLE THUCUNG --  Thú cưng
(
	MATC VARCHAR(5) NOT NULL,
	MAGIONG VARCHAR (5),
	DONGIA INT,
	CONSTRAINT PK_THUCUNG PRIMARY KEY (MATC)
)

CREATE TABLE HOADON(
	MAHD VARCHAR(10) NOT NULL,
	NGAYLAP DATETIME,
	NGUOILAPHD VARCHAR(5),
	MAKH VARCHAR(5),
	MAKM VARCHAR(10),
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD)
)

CREATE TABLE CTHOADONTHUCUNG(
	MAHD VARCHAR(10) NOT NULL,
	STT INT NOT NULL,
	MATC VARCHAR(5),
	SOLUONG INT,
	DONGIA INT,
	CONSTRAINT PK_CTHOADONTHUCUNG PRIMARY KEY (MAHD, STT)
)

CREATE TABLE CTHOADONSANPHAM(
	MAHD VARCHAR(10) NOT NULL,
	STT INT NOT NULL,
	MASP VARCHAR(5),
	SOLUONG INT,
	DONGIA INT,
	CONSTRAINT PK_CTHOADONSANPHAM PRIMARY KEY (MAHD, STT)
)


CREATE TABLE KHUYENMAI(
	MAKM VARCHAR(10) NOT NULL,--xem như mã coupon
	GIATRIKM INT , --vd: giảm giá tối đa 50000
	NGAYBD DATETIME,
	NGAYKT DATETIME,
	CONSTRAINT PK_KHUYENMAI PRIMARY KEY (MAKM)
)

CREATE TABLE CHUCVU(
	MACV VARCHAR(10) NOT NULL,
	DIENGIAI NVARCHAR(100)
	CONSTRAINT PK_CHUCVU PRIMARY KEY (MACV)
)

CREATE TABLE KHACHHANG(
	MAKH VARCHAR (5) NOT NULL,
	TENKH NVARCHAR(50),
	DIACHI NVARCHAR(200),
	SDT VARCHAR(12),
	CMND VARCHAR(10),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)

CREATE TABLE SANPHAM(
	MASP VARCHAR(5),
	LOAI VARCHAR(3),
	TENSP VARCHAR(20),
	DONGIA INT,
	CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
)
--------------------------------------TẠO RÀNG BUỘC KHÓA NGOẠI
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (NGUOILAPHD) REFERENCES NHANVIEN (MANV)
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHUYENMAI FOREIGN KEY (MAKM) REFERENCES KHUYENMAI (MAKM)

ALTER TABLE CTHOADONTHUCUNG ADD CONSTRAINT FK_CTHOADONTHUCUNG_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD)
ALTER TABLE CTHOADONTHUCUNG ADD CONSTRAINT FK_CTHOADONTHUCUNG_THUCUNG FOREIGN KEY (MATC) REFERENCES THUCUNG(MATC)

ALTER TABLE CTHOADONSANPHAM ADD CONSTRAINT FK_CTHOADONSANPHAM_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD)
ALTER TABLE CTHOADONSANPHAM ADD CONSTRAINT FK_CTHOADONSANPHAM_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE THUCUNG ADD CONSTRAINT FK_THUCUNG_CHITIETLOAI FOREIGN KEY (MAGIONG) REFERENCES CHITIETLOAI(MAGIONG)

ALTER TABLE CHITIETLOAI ADD CONSTRAINT FK_CHITIETLOAI_MALOAI FOREIGN KEY (MALOAI) REFERENCES LOAI(MALOAI)

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CHUCVU FOREIGN KEY(CHUCVU) REFERENCES CHUCVU(MACV)

ALTER TABLE	SANPHAM ADD CONSTRAINT FK_SANPHAM_LOAI FOREIGN KEY (LOAI) REFERENCES LOAI(MALOAI) 
-- CHITIETHOADON ----> THUCUNG / SANPHAM?
