/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameMain;
import Data.Data;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.DefaultButtonModel;
import javax.swing.text.JTextComponent;
import javax.imageio.ImageIO;

/**
 *
 * @author voanh
 */
import javax.swing.ImageIcon;
public class jFMain extends javax.swing.JFrame {
    static String id="";
    static String maChucVu;
    static String mk="";

    static String errorText = "Tên đăng nhập hoặc mật khẩu không hợp lệ !";
    
    
    boolean bThongTinCaNhan = false;
    boolean bQuanLyNhanVien = false;
    boolean bQuanLyLoaiSanPham = false;
    boolean bQuanLyKho = false;
    boolean bQuanLyThuChi = false;

    
    /**
     * Creates new form jFMain
     */
    public jFMain() {
        
         Data d = new Data();
        
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        
        

        
        btn_ThongTinCaNhan.setModel(new FixedStateButtonModel());
        btn_QuanLyNhanVien.setModel(new FixedStateButtonModel());
        btn_QuanLyLoaiSanPham.setModel(new FixedStateButtonModel());
        btn_QuanLyThuChi.setModel(new FixedStateButtonModel());
        btn_Thoat.setModel(new FixedStateButtonModel());
        btn_QuanLyKho.setModel(new FixedStateButtonModel());
        
        
        //
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_ThongTinCaNhan.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
        //
        
        SetAllTextFieldDisable();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_QuanLyNhanVien = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jpn_Table = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTF_MANV = new javax.swing.JTextField();
        jTF_HoTen = new javax.swing.JTextField();
        jTF_DiaChi = new javax.swing.JTextField();
        jTF_SDT = new javax.swing.JTextField();
        jCB_GioiTinh = new javax.swing.JComboBox<>();
        jDC_NgaySinh = new com.toedter.calendar.JDateChooser();
        jTF_SOCMND = new javax.swing.JTextField();
        btn_QuanLyKho2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTF_ChucVu = new javax.swing.JTextField();
        jTF_Luong = new javax.swing.JTextField();
        btn_QuanLyKho3 = new javax.swing.JButton();
        btn_QuanLyKho1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTF_TenTk = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTB_ThongTin = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTF_MANV1 = new javax.swing.JTextField();
        jTF_HoTen1 = new javax.swing.JTextField();
        jTF_DiaChi1 = new javax.swing.JTextField();
        jTF_SDT1 = new javax.swing.JTextField();
        jCB_GioiTinh1 = new javax.swing.JComboBox<>();
        jDC_NgaySinh1 = new com.toedter.calendar.JDateChooser();
        jTF_SOCMND1 = new javax.swing.JTextField();
        btn_QuanLyKho4 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTF_ChucVu1 = new javax.swing.JTextField();
        jTF_Luong1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTF_TenTk1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Thoat = new javax.swing.JButton();
        btn_QuanLyNhanVien = new javax.swing.JButton();
        btn_QuanLyLoaiSanPham = new javax.swing.JButton();
        btn_QuanLyThuChi = new javax.swing.JButton();
        btn_QuanLyKho = new javax.swing.JButton();
        btn_ThongTinCaNhan = new javax.swing.JButton();
        jpn_ThongTinCaNhan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jpn_QuanLyKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpn_QuanLyLoaiSanPham = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpn_QuanLyThuChi = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImages(null);
        setLocationByPlatform(true);
        setName("fLogin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpn_QuanLyNhanVien.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLyNhanVien.setForeground(new java.awt.Color(240, 240, 240));
        jpn_QuanLyNhanVien.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_QuanLyNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("QUẢN LÝ NHÂN VIÊN");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_QuanLyNhanVien.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1040, 100));

        jpn_Table.setBackground(new java.awt.Color(0, 120, 120));
        jpn_Table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpn_QuanLyNhanVien.add(jpn_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        jPanel6.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 120, 120));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Họ Tên");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 119, 30));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Giới Tính");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 119, 30));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ngày Sinh");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 119, 30));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Số Điện Thoại");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 119, 30));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Địa Chỉ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 119, 30));

        jTF_MANV.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_MANV.setToolTipText("Sundep trai");
        jTF_MANV.setBorder(null);
        jTF_MANV.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jTF_MANV.setName(""); // NOI18N
        jTF_MANV.setSelectionColor(new java.awt.Color(255, 51, 153));
        jPanel1.add(jTF_MANV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, 30));

        jTF_HoTen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_HoTen.setBorder(null);
        jTF_HoTen.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, 30));

        jTF_DiaChi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_DiaChi.setBorder(null);
        jTF_DiaChi.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 190, 30));

        jTF_SDT.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SDT.setBorder(null);
        jTF_SDT.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 190, 30));

        jCB_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "null" }));
        jPanel1.add(jCB_GioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 100, 30));

        jDC_NgaySinh.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDC_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, 30));

        jTF_SOCMND.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SOCMND.setBorder(null);
        jTF_SOCMND.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_SOCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 130, 30));

        btn_QuanLyKho2.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho2.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho2.setText("Xác Nhận");
        btn_QuanLyKho2.setBorder(null);
        btn_QuanLyKho2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho2.setFocusable(false);
        btn_QuanLyKho2.setName(""); // NOI18N
        btn_QuanLyKho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyKho2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_QuanLyKho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 90, 30));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Mã Nhân Viên");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 119, 30));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Chức Vụ");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 60, 30));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Lương");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 60, 30));

        jTF_ChucVu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_ChucVu.setBorder(null);
        jTF_ChucVu.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_ChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 130, 30));

        jTF_Luong.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_Luong.setBorder(null);
        jTF_Luong.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_Luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 130, 30));

        btn_QuanLyKho3.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho3.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho3.setText("Sửa ");
        btn_QuanLyKho3.setBorder(null);
        btn_QuanLyKho3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho3.setFocusable(false);
        btn_QuanLyKho3.setName(""); // NOI18N
        btn_QuanLyKho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyKho3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_QuanLyKho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 90, 30));

        btn_QuanLyKho1.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho1.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho1.setText("Xóa");
        btn_QuanLyKho1.setBorder(null);
        btn_QuanLyKho1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho1.setFocusable(false);
        btn_QuanLyKho1.setName(""); // NOI18N
        btn_QuanLyKho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyKho1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_QuanLyKho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 90, 30));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tên TK");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 60, 30));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Mật Khẩu");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 60, 30));

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, 30));

        jTF_TenTk.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_TenTk.setBorder(null);
        jTF_TenTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TenTkActionPerformed(evt);
            }
        });
        jPanel1.add(jTF_TenTk, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 130, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Số CMND");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 70, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, 10));

        jPanel6.add(jPanel1);
        jPanel1.setBounds(230, -8, 787, 460);

        jButton3.setText("Tìm kiếm");

        jLabel18.setText("Tìm kiếm nhân viên theo chức vụ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(90, 90, 90))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
        );

        jTextField5.getAccessibleContext().setAccessibleName("");

        jPanel6.add(jPanel4);
        jPanel4.setBounds(10, 10, 210, 103);

        jTB_ThongTin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTB_ThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NV0011", "Võ Anh Tuấn"},
                {"1", " Võ Văn B"},
                {"11", null},
                {"11", null},
                {"11", null},
                {"11", null},
                {"11", null},
                {"11", null}
            },
            new String [] {
                "MÃ NV", "Họ Tên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTB_ThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTB_ThongTinMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTB_ThongTinMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTB_ThongTin);
        if (jTB_ThongTin.getColumnModel().getColumnCount() > 0) {
            jTB_ThongTin.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTB_ThongTin.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 210, 320);

        jTabbedPane1.addTab("Thông Tin Nhân Viên", new javax.swing.ImageIcon(getClass().getResource("/Image/Cat Profile_25px.png")), jPanel6); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0, 120, 120));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Họ Tên");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 119, 30));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Giới Tính");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 119, 30));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Ngày Sinh");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 119, 30));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Số Điện Thoại");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 119, 30));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Địa Chỉ");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 119, 30));

        jTF_MANV1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_MANV1.setToolTipText("Sundep trai");
        jTF_MANV1.setBorder(null);
        jTF_MANV1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jTF_MANV1.setName(""); // NOI18N
        jTF_MANV1.setSelectionColor(new java.awt.Color(255, 51, 153));
        jPanel5.add(jTF_MANV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 100, 30));

        jTF_HoTen1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_HoTen1.setBorder(null);
        jTF_HoTen1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_HoTen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, 30));

        jTF_DiaChi1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_DiaChi1.setBorder(null);
        jTF_DiaChi1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_DiaChi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 190, 30));

        jTF_SDT1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SDT1.setBorder(null);
        jTF_SDT1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_SDT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 190, 30));

        jCB_GioiTinh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "null" }));
        jPanel5.add(jCB_GioiTinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, 30));

        jDC_NgaySinh1.setDateFormatString("dd/MM/yyyy");
        jPanel5.add(jDC_NgaySinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 190, 30));

        jTF_SOCMND1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SOCMND1.setBorder(null);
        jTF_SOCMND1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_SOCMND1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 130, 30));

        btn_QuanLyKho4.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho4.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho4.setText("Xác Nhận");
        btn_QuanLyKho4.setBorder(null);
        btn_QuanLyKho4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho4.setFocusable(false);
        btn_QuanLyKho4.setName(""); // NOI18N
        btn_QuanLyKho4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyKho4ActionPerformed(evt);
            }
        });
        jPanel5.add(btn_QuanLyKho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 90, 30));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Mã Nhân Viên");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 119, 30));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Chức Vụ");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 60, 30));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Lương");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 60, 30));

        jTF_ChucVu1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_ChucVu1.setBorder(null);
        jTF_ChucVu1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_ChucVu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 130, 30));

        jTF_Luong1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_Luong1.setBorder(null);
        jTF_Luong1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_Luong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 130, 30));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Tên TK");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 60, 30));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Mật Khẩu");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 60, 30));

        jPasswordField2.setText("jPasswordField1");
        jPanel5.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 130, 30));

        jTF_TenTk1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_TenTk1.setBorder(null);
        jTF_TenTk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TenTk1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTF_TenTk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 130, 30));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Số CMND");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 70, 30));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 20, 310));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 250, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1015, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Thêm Nhân Viên", new javax.swing.ImageIcon(getClass().getResource("/Image/Cat Profile_25px.png")), jPanel7); // NOI18N

        jpn_QuanLyNhanVien.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1020, 480));
        jTabbedPane1.getAccessibleContext().setAccessibleName("1");

        jpn_QuanLyNhanVien.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, 540, 10));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cat-profile-75.png"))); // NOI18N
        jLabel2.setText("PETS STORE");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chào  TUANKYOU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 120, 215));

        btn_Thoat.setBackground(new java.awt.Color(0, 120, 215));
        btn_Thoat.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setText("Thoát");
        btn_Thoat.setBorder(null);
        btn_Thoat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Thoat.setFocusable(false);
        btn_Thoat.setName(""); // NOI18N
        btn_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseExited(evt);
            }
        });

        btn_QuanLyNhanVien.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyNhanVien.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyNhanVien.setText("Quản Lý Nhân Viên");
        btn_QuanLyNhanVien.setBorder(null);
        btn_QuanLyNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyNhanVien.setFocusable(false);
        btn_QuanLyNhanVien.setName(""); // NOI18N
        btn_QuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyNhanVienMouseExited(evt);
            }
        });
        btn_QuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyNhanVienActionPerformed(evt);
            }
        });

        btn_QuanLyLoaiSanPham.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyLoaiSanPham.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyLoaiSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyLoaiSanPham.setText("Quản Lý Loại Sản Phẩm");
        btn_QuanLyLoaiSanPham.setBorder(null);
        btn_QuanLyLoaiSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyLoaiSanPham.setFocusable(false);
        btn_QuanLyLoaiSanPham.setName(""); // NOI18N
        btn_QuanLyLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyLoaiSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyLoaiSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyLoaiSanPhamMouseExited(evt);
            }
        });
        btn_QuanLyLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyLoaiSanPhamActionPerformed(evt);
            }
        });

        btn_QuanLyThuChi.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyThuChi.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyThuChi.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyThuChi.setText("Quản Lý Thu Chi");
        btn_QuanLyThuChi.setBorder(null);
        btn_QuanLyThuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyThuChi.setFocusable(false);
        btn_QuanLyThuChi.setName(""); // NOI18N
        btn_QuanLyThuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyThuChiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyThuChiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyThuChiMouseExited(evt);
            }
        });

        btn_QuanLyKho.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho.setText("Quản Lý Kho");
        btn_QuanLyKho.setBorder(null);
        btn_QuanLyKho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho.setFocusable(false);
        btn_QuanLyKho.setName(""); // NOI18N
        btn_QuanLyKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseExited(evt);
            }
        });
        btn_QuanLyKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyKhoActionPerformed(evt);
            }
        });

        btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        btn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThongTinCaNhan.setText("Thông Tin Cá Nhân");
        btn_ThongTinCaNhan.setBorder(null);
        btn_ThongTinCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ThongTinCaNhan.setFocusable(false);
        btn_ThongTinCaNhan.setName(""); // NOI18N
        btn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseExited(evt);
            }
        });
        btn_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyThuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyThuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jpn_ThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_ThongTinCaNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 96, 100));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Địa Chỉ");
        jpn_ThongTinCaNhan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 30));

        jLabel4.setBackground(new java.awt.Color(0, 96, 100));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ Tên ");
        jpn_ThongTinCaNhan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 30));

        jLabel5.setBackground(new java.awt.Color(0, 96, 100));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới Tính");
        jpn_ThongTinCaNhan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 30));

        jLabel6.setBackground(new java.awt.Color(0, 96, 100));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Sinh");
        jpn_ThongTinCaNhan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 30));

        jLabel7.setBackground(new java.awt.Color(0, 96, 100));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Điện Thoại");
        jpn_ThongTinCaNhan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 38));

        jTextField1.setBackground(new java.awt.Color(0, 120, 120));
        jTextField1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Củ Chi, Việt Nam");
        jTextField1.setBorder(null);
        jpn_ThongTinCaNhan.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 374, 30));

        jComboBox1.setBackground(new java.awt.Color(0, 120, 120));
        jComboBox1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jComboBox1.setBorder(null);
        jpn_ThongTinCaNhan.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 30));

        jDateChooser1.setBackground(new java.awt.Color(0, 0, 0));
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jpn_ThongTinCaNhan.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 30));

        jTextField2.setBackground(new java.awt.Color(0, 120, 120));
        jTextField2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Võ Anh Tuấn");
        jTextField2.setBorder(null);
        jpn_ThongTinCaNhan.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 30));

        jTextField3.setBackground(new java.awt.Color(0, 120, 120));
        jTextField3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("001672038391");
        jTextField3.setBorder(null);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 200, 30));

        jButton1.setBackground(new java.awt.Color(0, 120, 215));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xác Nhận");
        jButton1.setBorder(null);
        jpn_ThongTinCaNhan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 125, 47));

        jButton2.setBackground(new java.awt.Color(0, 120, 215));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Chỉnh Sửa");
        jButton2.setBorder(null);
        jpn_ThongTinCaNhan.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 125, 47));
        jpn_ThongTinCaNhan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 374, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("THÔNG TIN CÁ NHÂN");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_ThongTinCaNhan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1040, 100));

        jLabel13.setForeground(new java.awt.Color(255, 153, 102));
        jLabel13.setText("*Số điện thoại không hợp lệ");
        jpn_ThongTinCaNhan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, 30));

        jLabel14.setForeground(new java.awt.Color(255, 153, 102));
        jLabel14.setText("*Tên đăng nhập không chứa ký tự đặt biệt");
        jpn_ThongTinCaNhan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, 30));

        jLabel15.setBackground(new java.awt.Color(0, 96, 100));
        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Số CMND");
        jpn_ThongTinCaNhan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 100, 38));

        jTextField4.setBackground(new java.awt.Color(0, 120, 120));
        jTextField4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("001672038391");
        jTextField4.setBorder(null);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 200, 30));

        jLabel16.setForeground(new java.awt.Color(255, 153, 102));
        jLabel16.setText("*Số CMND không hợp lệ");
        jpn_ThongTinCaNhan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, 30));
        jpn_ThongTinCaNhan.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, -1));

        jpn_QuanLyKho.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLyKho.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel10.setText("Quản Lý Kho");

        javax.swing.GroupLayout jpn_QuanLyKhoLayout = new javax.swing.GroupLayout(jpn_QuanLyKho);
        jpn_QuanLyKho.setLayout(jpn_QuanLyKhoLayout);
        jpn_QuanLyKhoLayout.setHorizontalGroup(
            jpn_QuanLyKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyKhoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLyKhoLayout.setVerticalGroup(
            jpn_QuanLyKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyKhoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        jpn_QuanLyLoaiSanPham.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLyLoaiSanPham.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel9.setText("Quản Lý Loại Sản Phẩm");

        javax.swing.GroupLayout jpn_QuanLyLoaiSanPhamLayout = new javax.swing.GroupLayout(jpn_QuanLyLoaiSanPham);
        jpn_QuanLyLoaiSanPham.setLayout(jpn_QuanLyLoaiSanPhamLayout);
        jpn_QuanLyLoaiSanPhamLayout.setHorizontalGroup(
            jpn_QuanLyLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyLoaiSanPhamLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLyLoaiSanPhamLayout.setVerticalGroup(
            jpn_QuanLyLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyLoaiSanPhamLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        jpn_QuanLyThuChi.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLyThuChi.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel11.setText("Quản Lý Thu Chi");

        javax.swing.GroupLayout jpn_QuanLyThuChiLayout = new javax.swing.GroupLayout(jpn_QuanLyThuChi);
        jpn_QuanLyThuChi.setLayout(jpn_QuanLyThuChiLayout);
        jpn_QuanLyThuChiLayout.setHorizontalGroup(
            jpn_QuanLyThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyThuChiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLyThuChiLayout.setVerticalGroup(
            jpn_QuanLyThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyThuChiLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyThuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyThuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ExitProgram();
    }//GEN-LAST:event_formWindowClosing

    private void btn_QuanLyNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyNhanVienMouseEntered
        if(bQuanLyNhanVien == false)
            btn_QuanLyNhanVien.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLyNhanVienMouseEntered

    private void btn_QuanLyLoaiSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyLoaiSanPhamMouseEntered
        if(bQuanLyLoaiSanPham == false)
            btn_QuanLyLoaiSanPham.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLyLoaiSanPhamMouseEntered

    private void btn_QuanLyKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseEntered
        if(bQuanLyKho == false)
            btn_QuanLyKho.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLyKhoMouseEntered

    private void btn_QuanLyThuChiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThuChiMouseEntered
        if(bQuanLyThuChi==false)
            btn_QuanLyThuChi.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLyThuChiMouseEntered

    private void btn_ThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseEntered
        btn_Thoat.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_ThoatMouseEntered

    private void btn_QuanLyNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyNhanVienMouseExited
        if(bQuanLyNhanVien==false)
            btn_QuanLyNhanVien.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLyNhanVienMouseExited

    private void btn_QuanLyLoaiSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyLoaiSanPhamMouseExited
        if(bQuanLyLoaiSanPham==false)
            btn_QuanLyLoaiSanPham.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLyLoaiSanPhamMouseExited

    private void btn_QuanLyKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseExited
        if(bQuanLyKho==false)
            btn_QuanLyKho.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLyKhoMouseExited

    private void btn_QuanLyThuChiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThuChiMouseExited
        if(bQuanLyThuChi==false)
            btn_QuanLyThuChi.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLyThuChiMouseExited

    private void btn_ThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseExited
        btn_Thoat.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_ThoatMouseExited

    private void btn_ThongTinCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseEntered
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseEntered

    private void btn_ThongTinCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseExited
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseExited

    private void btn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_ThongTinCaNhan.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseClicked

    private void btn_QuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyNhanVienMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLyNhanVien.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLyNhanVien = true;
        SetAllPanelDissapear();
        jpn_QuanLyNhanVien.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyNhanVienMouseClicked

    private void btn_QuanLyLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyLoaiSanPhamMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLyLoaiSanPham.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLyLoaiSanPham = true;
        SetAllPanelDissapear();
        jpn_QuanLyLoaiSanPham.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyLoaiSanPhamMouseClicked

    private void btn_QuanLyKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLyKho.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLyKho = true;
        SetAllPanelDissapear();
        jpn_QuanLyThuChi.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyKhoMouseClicked

    private void btn_QuanLyThuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThuChiMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLyThuChi.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLyThuChi = true;
        SetAllPanelDissapear();
        jpn_QuanLyKho.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyThuChiMouseClicked

    private void btn_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongTinCaNhanActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar))|| vchar == KeyEvent.VK_BACKSPACE || vchar == KeyEvent.VK_DELETE){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void btn_QuanLyKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QuanLyKhoActionPerformed

    private void jTB_ThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTB_ThongTinMouseClicked
        
        try{
            int row = jTB_ThongTin.getSelectedRow();
            String manv = jTB_ThongTin.getModel().getValueAt(row,0).toString();
            String hoten = jTB_ThongTin.getModel().getValueAt(row,1).toString();
            String gioiTinh = jTB_ThongTin.getModel().getValueAt(row,2).toString();
            String ngaySinh  = jTB_ThongTin.getModel().getValueAt(row,3).toString();
            String diaChi = jTB_ThongTin.getModel().getValueAt(row,4).toString();
            String sdt = jTB_ThongTin.getModel().getValueAt(row,5).toString();
            String ChucVu = jTB_ThongTin.getModel().getValueAt(row,6).toString();
            String luong = jTB_ThongTin.getModel().getValueAt(row,7).toString();
            String soCMND= jTB_ThongTin.getModel().getValueAt(row,8).toString();
            jTF_SOCMND.setText(soCMND);
            jTF_MANV.setText(jTB_ThongTin.getModel().getValueAt(row,0).toString());
            jTF_HoTen.setText(jTB_ThongTin.getModel().getValueAt(row,1).toString());
            jCB_GioiTinh.setSelectedItem(jTB_ThongTin.getModel().getValueAt(row,2).toString());
            java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(ngaySinh);
            jTF_DiaChi.setText(jTB_ThongTin.getModel().getValueAt(row,4).toString());
            jDC_NgaySinh.setDate(date);
            jTF_SDT.setText(jTB_ThongTin.getModel().getValueAt(row,5).toString());
            jTF_TenTk.setText(jTB_ThongTin.getModel().getValueAt(row,6).toString());
            jTF_Luong.setText(jTB_ThongTin.getModel().getValueAt(row,7).toString());
            
        }catch (Exception e){
            jTF_SOCMND.setText("");
            jTF_MANV.setText("");
            jTF_HoTen.setText("");
            jCB_GioiTinh.setSelectedItem("null");
            jTF_DiaChi.setText("");
            jDC_NgaySinh.setDate(new Date(-1));
            jTF_SDT.setText("");
            jTF_TenTk.setText("");
            jTF_Luong.setText("");
        }
    }//GEN-LAST:event_jTB_ThongTinMouseClicked

    private void btn_QuanLyLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyLoaiSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QuanLyLoaiSanPhamActionPerformed

    private void btn_QuanLyKho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyKho3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_QuanLyKho3ActionPerformed

    private void btn_QuanLyKho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyKho2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Đã sửa thành công.");
    }//GEN-LAST:event_btn_QuanLyKho2ActionPerformed

    private void jTF_TenTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TenTkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TenTkActionPerformed

    private void btn_QuanLyKho4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyKho4ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Đã thêm thành công.");
    }//GEN-LAST:event_btn_QuanLyKho4ActionPerformed

    private void jTF_TenTk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TenTk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TenTk1ActionPerformed

    private void btn_QuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QuanLyNhanVienActionPerformed

    private void btn_QuanLyKho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyKho1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/images/Cat Profile_25px.png");
        int output = JOptionPane.showConfirmDialog(this,"Bạn có thật sự muốn xóa nhân viên này?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, icon);
        if(output==JOptionPane.YES_OPTION){
            //System.exit(0);
            JOptionPane.showMessageDialog(this, "Đã xóa nhân viên.");
            //JOptionPane.showConfirmDialog(this,"Đã xóa nhân viên","Thông báo",-1,JOptionPane.QUESTION_MESSAGE,icon);
        }
        else
            return;
    }//GEN-LAST:event_btn_QuanLyKho1ActionPerformed

    private void jTB_ThongTinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTB_ThongTinMousePressed
        // TODO add your handling code here:
        //Lấy ra MSNV -> Search trong database -> And thông tin sau khi search vào 
        
    }//GEN-LAST:event_jTB_ThongTinMousePressed
    
    
    void SetAllTextFieldDisable(){
        jTF_SOCMND.setEnabled(false);
        jTF_MANV.setEnabled(false);
        jTF_HoTen.setEnabled(false);
        jCB_GioiTinh.setEnabled(false);
        jTF_DiaChi.setEnabled(false);
        jDC_NgaySinh.setEnabled(false);
        jTF_SDT.setEnabled(false);
        jTF_TenTk.setEnabled(false);
        jTF_Luong.setEnabled(false);
        //jpn_Account.setVisible(false);
    }
    
    void SetAllTextFieldEnable(){
        jTF_SOCMND.setEnabled(true);
        jTF_MANV.setEnabled(true);
        jTF_HoTen.setEnabled(true);
        jCB_GioiTinh.setEnabled(true);
        jTF_DiaChi.setEnabled(true);
        jDC_NgaySinh.setEnabled(true);
        jTF_SDT.setEnabled(true);
        jTF_TenTk.setEnabled(true);
        jTF_Luong.setEnabled(true);
       // jpn_Account.setVisible(false);
    }
    
    void SetColorAllButton(java.awt.Color jColor ){
        btn_ThongTinCaNhan.setBackground(jColor);
        btn_QuanLyLoaiSanPham.setBackground(jColor);
        btn_QuanLyNhanVien.setBackground(jColor);
        btn_QuanLyThuChi.setBackground(jColor);
        btn_Thoat.setBackground(jColor);
        btn_QuanLyKho.setBackground(jColor);
    }
    
    

    
    void SetFalseAllButton(){
        bThongTinCaNhan = false;
        bQuanLyNhanVien = false;
        bQuanLyLoaiSanPham = false;
        bQuanLyKho = false;
        bQuanLyThuChi = false;
    }
    void SetAllPanelDissapear(){
        jpn_QuanLyKho.setVisible(false);
        jpn_QuanLyNhanVien.setVisible(false);
        jpn_QuanLyLoaiSanPham.setVisible(false);
        jpn_QuanLyThuChi.setVisible(false);
        jpn_ThongTinCaNhan.setVisible(false);
    }
    void ExitProgram(){
        int output = JOptionPane.showConfirmDialog(this,"Bạn có thật sự muốn thoát không ?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(output==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else
            return;
    }
    /**
     * @param args the command line arguments
     */
    
    public class FixedStateButtonModel extends DefaultButtonModel    {

        @Override
        public boolean isPressed() {
            return false;
        }

        @Override
        public boolean isRollover() {
            return false;
        }

        @Override
        public void setRollover(boolean b) {
            //NOOP
        }

    }
    
    public static void mmmain(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_QuanLyKho;
    private javax.swing.JButton btn_QuanLyKho1;
    private javax.swing.JButton btn_QuanLyKho2;
    private javax.swing.JButton btn_QuanLyKho3;
    private javax.swing.JButton btn_QuanLyKho4;
    private javax.swing.JButton btn_QuanLyLoaiSanPham;
    private javax.swing.JButton btn_QuanLyNhanVien;
    private javax.swing.JButton btn_QuanLyThuChi;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_ThongTinCaNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCB_GioiTinh;
    private javax.swing.JComboBox<String> jCB_GioiTinh1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDC_NgaySinh;
    private com.toedter.calendar.JDateChooser jDC_NgaySinh1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTB_ThongTin;
    private javax.swing.JTextField jTF_ChucVu;
    private javax.swing.JTextField jTF_ChucVu1;
    private javax.swing.JTextField jTF_DiaChi;
    private javax.swing.JTextField jTF_DiaChi1;
    private javax.swing.JTextField jTF_HoTen;
    private javax.swing.JTextField jTF_HoTen1;
    private javax.swing.JTextField jTF_Luong;
    private javax.swing.JTextField jTF_Luong1;
    private javax.swing.JTextField jTF_MANV;
    private javax.swing.JTextField jTF_MANV1;
    private javax.swing.JTextField jTF_SDT;
    private javax.swing.JTextField jTF_SDT1;
    private javax.swing.JTextField jTF_SOCMND;
    private javax.swing.JTextField jTF_SOCMND1;
    private javax.swing.JTextField jTF_TenTk;
    private javax.swing.JTextField jTF_TenTk1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel jpn_QuanLyKho;
    private javax.swing.JPanel jpn_QuanLyLoaiSanPham;
    private javax.swing.JPanel jpn_QuanLyNhanVien;
    private javax.swing.JPanel jpn_QuanLyThuChi;
    private javax.swing.JPanel jpn_Table;
    private javax.swing.JPanel jpn_ThongTinCaNhan;
    // End of variables declaration//GEN-END:variables
}
