/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameMain;
import Data.Data;
import static JFrameMain.jF_ChuCuaHang.Color;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.DefaultButtonModel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.updateComponentTreeUI;

/**
 *
 * @author voanh
 */
public class jFNhanVienKho extends javax.swing.JFrame {
    static String id="";
    static String maChucVu;
    static String mk="";

    static String errorText = "Tên đăng nhập hoặc mật khẩu không hợp lệ !";
    
    
    boolean bThongTinCaNhan = false;
    boolean bQuanLySanPham = false;
    boolean bQuanLyKho = false;
    boolean is_ChinhSua_ThongTinCaNhan = false;
    static Class_Color Color = new Class_Color();
    /**
     * Creates new form jFMain
     */
    public jFNhanVienKho() {
        
        Data d = new Data();
        
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        
        
        
        btn_ThongTinCaNhan.setModel(new FixedStateButtonModel());
        btn_QuanLySanPham.setModel(new FixedStateButtonModel());
        btn_QuanLyKho.setModel(new FixedStateButtonModel());
        btn_Thoat.setModel(new FixedStateButtonModel());

        
        
        //
        btn_ThongTinCaNhan.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
        ThongTinCaNhan_SetAllThingDefault();
        //
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Thoat = new javax.swing.JButton();
        btn_QuanLySanPham = new javax.swing.JButton();
        btn_QuanLyKho = new javax.swing.JButton();
        btn_ThongTinCaNhan = new javax.swing.JButton();
        jpn_ThongTinCaNhan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTF_DiaChi_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jCB_GioiTinh_pn_ThongTinCaNhan = new javax.swing.JComboBox<>();
        jDC_NgaySinh_pn_ThongTinCaNhan = new com.toedter.calendar.JDateChooser();
        jTF_Hoten_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jTF_DienThoai_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jBtn_XacNhan_pn_ThongTinCaNhan = new javax.swing.JButton();
        jBtn_ChinhSua_pn_ThongTinCaNhan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLb_Error_SDT = new javax.swing.JLabel();
        jLb_Error_HoTen = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTF_SoCMND_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jLb_Error_SoCMND = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jpn_QuanLySanPham = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_BangSP_pn_BangSP_pn_QLSP = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jpn_ThemSanPham_QLSP = new javax.swing.JPanel();
        cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP = new javax.swing.JComboBox<>();
        cmbx_LoaiSP_pn_ThemSP_pn_QLSP = new javax.swing.JComboBox<>();
        cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP = new javax.swing.JComboBox<>();
        tf_GiaVatNuoi_pn_ThemSP_pn_QLSP = new javax.swing.JTextField();
        tf_GiaSP_pn_ThemSP_pn_QLSP = new javax.swing.JTextField();
        tf_MaVatNuoi_pn_ThemSP_pn_QLSP = new javax.swing.JTextField();
        tf_MaSP_pn_ThemSP_pn_QLSP = new javax.swing.JTextField();
        tf_TenSP_pn_ThemSP_pn_QLSP = new javax.swing.JTextField();
        btn_XacNhan_pn_ThemSP_pn_QLSP = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jpn_SuaSanPham_QLSP = new javax.swing.JPanel();
        cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP = new javax.swing.JComboBox<>();
        tf_TenSP_pn_SuaSP_pn_QLSP = new javax.swing.JTextField();
        tf_GiaVatNuoi_pn_SuaSP_pn_QLSP = new javax.swing.JTextField();
        tf_GiaSP_pn_SuaSP_pn_QLSP = new javax.swing.JTextField();
        cmbx_LoaiSP_pn_SuaSP_pn_QLSP = new javax.swing.JComboBox<>();
        cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP = new javax.swing.JComboBox<>();
        btn_XacNhan_pn_SuaSP_pn_QLSP = new javax.swing.JButton();
        tf_MaSP_pn_SuaSP_pn_QLSP = new javax.swing.JTextField();
        tf_MaVatNuoi_pn_SuaSP_pn_QLSP = new javax.swing.JTextField();
        jP_XoaSanPham_QLSP = new javax.swing.JPanel();
        cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP = new javax.swing.JComboBox<>();
        cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP = new javax.swing.JComboBox<>();
        btn_XacNhan_pn_XoaSP_pn_QLSP = new javax.swing.JButton();
        cmbx_LoaiSP_pn_XoaSP_pn_QLSP = new javax.swing.JComboBox<>();
        tf_MaSP_pn_XoaSP_pn_QLSP = new javax.swing.JTextField();
        tf_MaVatNuoi_pn_XoaSP_pn_QLSP = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jpn_QuanLyKho = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jpn_QuanLyKho_BangVatNuoi = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho = new javax.swing.JTable();
        tf_SoLuong_pn_BangVatNuoi_pn_QLKho = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jpn_QuanLyKho_BangSanPham = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_BangSP_pn_BangSP_pn_QLKho = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tf_SoLuong_pn_BangSP_pn_QLKho = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbx_LoaiSP_pn_QLKho = new javax.swing.JComboBox<>();
        cmbx_LoaiVatNuoi_pn_QLKho = new javax.swing.JComboBox<>();
        cmbx_GiongVatNuoi_pn_QLKho = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImages(null);
        setLocationByPlatform(true);
        setName("fLogin"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cat-profile-75.png"))); // NOI18N
        jLabel2.setText("PETS STORE");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chào  TUANKYOU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(32, 78, 80));

        btn_Thoat.setBackground(new java.awt.Color(32, 78, 80));
        btn_Thoat.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Exit_Sign_48px.png"))); // NOI18N
        btn_Thoat.setBorder(null);
        btn_Thoat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Thoat.setFocusable(false);
        btn_Thoat.setName(""); // NOI18N
        btn_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseExited(evt);
            }
        });

        btn_QuanLySanPham.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLySanPham.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLySanPham.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLySanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Product_Documents_50px.png"))); // NOI18N
        btn_QuanLySanPham.setBorder(null);
        btn_QuanLySanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLySanPham.setFocusable(false);
        btn_QuanLySanPham.setName(""); // NOI18N
        btn_QuanLySanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamMouseExited(evt);
            }
        });

        btn_QuanLyKho.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLyKho.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLyKho.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_House_50px.png"))); // NOI18N
        btn_QuanLyKho.setBorder(null);
        btn_QuanLyKho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho.setFocusable(false);
        btn_QuanLyKho.setName(""); // NOI18N
        btn_QuanLyKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseExited(evt);
            }
        });

        btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 64, 80));
        btn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Personal_Trainer_50px.png"))); // NOI18N
        btn_ThongTinCaNhan.setBorder(null);
        btn_ThongTinCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ThongTinCaNhan.setFocusable(false);
        btn_ThongTinCaNhan.setName(""); // NOI18N
        btn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseExited(evt);
            }
        });
        btn_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 64, 80));
        jpn_ThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_ThongTinCaNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("THÔNG TIN CÁ NHÂN");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_ThongTinCaNhan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1040, 100));

        jLabel3.setBackground(new java.awt.Color(0, 96, 100));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Địa Chỉ");
        jpn_ThongTinCaNhan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 30));

        jLabel4.setBackground(new java.awt.Color(0, 96, 100));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ Tên ");
        jpn_ThongTinCaNhan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 30));

        jLabel5.setBackground(new java.awt.Color(0, 96, 100));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới Tính");
        jpn_ThongTinCaNhan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 30));

        jLabel6.setBackground(new java.awt.Color(0, 96, 100));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Sinh");
        jpn_ThongTinCaNhan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 30));

        jLabel7.setBackground(new java.awt.Color(0, 96, 100));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Điện Thoại");
        jpn_ThongTinCaNhan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 38));

        jTF_DiaChi_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_DiaChi_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_DiaChi_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_DiaChi_pn_ThongTinCaNhan.setText("Củ Chi, Việt Nam");
        jTF_DiaChi_pn_ThongTinCaNhan.setBorder(null);
        jTF_DiaChi_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jpn_ThongTinCaNhan.add(jTF_DiaChi_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 374, 30));

        jCB_GioiTinh_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jCB_GioiTinh_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jCB_GioiTinh_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jCB_GioiTinh_pn_ThongTinCaNhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jCB_GioiTinh_pn_ThongTinCaNhan.setBorder(null);
        jpn_ThongTinCaNhan.add(jCB_GioiTinh_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 30));

        jDC_NgaySinh_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 0, 0));
        jDC_NgaySinh_pn_ThongTinCaNhan.setDateFormatString("dd/MM/yyyy");
        jpn_ThongTinCaNhan.add(jDC_NgaySinh_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 30));

        jTF_Hoten_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_Hoten_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_Hoten_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_Hoten_pn_ThongTinCaNhan.setText("Võ Anh Tuấn");
        jTF_Hoten_pn_ThongTinCaNhan.setBorder(null);
        jTF_Hoten_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jpn_ThongTinCaNhan.add(jTF_Hoten_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 30));

        jTF_DienThoai_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_DienThoai_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_DienThoai_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_DienThoai_pn_ThongTinCaNhan.setText("001672038391");
        jTF_DienThoai_pn_ThongTinCaNhan.setBorder(null);
        jTF_DienThoai_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTF_DienThoai_pn_ThongTinCaNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_DienThoai_pn_ThongTinCaNhanKeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTF_DienThoai_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 200, 30));

        jBtn_XacNhan_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        jBtn_XacNhan_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_XacNhan_pn_ThongTinCaNhan.setText("Xác Nhận");
        jBtn_XacNhan_pn_ThongTinCaNhan.setBorder(null);
        jBtn_XacNhan_pn_ThongTinCaNhan.setFocusable(false);
        jBtn_XacNhan_pn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jBtn_XacNhan_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 125, 47));

        jBtn_ChinhSua_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        jBtn_ChinhSua_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_ChinhSua_pn_ThongTinCaNhan.setText("Chỉnh Sửa");
        jBtn_ChinhSua_pn_ThongTinCaNhan.setBorder(null);
        jBtn_ChinhSua_pn_ThongTinCaNhan.setFocusable(false);
        jBtn_ChinhSua_pn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jBtn_ChinhSua_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 125, 47));
        jpn_ThongTinCaNhan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 374, -1));

        jLb_Error_SDT.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_SDT.setText("*Số điện thoại không hợp lệ");
        jpn_ThongTinCaNhan.add(jLb_Error_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, 30));

        jLb_Error_HoTen.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_HoTen.setText("*Tên đăng nhập không chứa ký tự đặc biệt");
        jpn_ThongTinCaNhan.add(jLb_Error_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, 30));

        jLabel15.setBackground(new java.awt.Color(0, 96, 100));
        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Số CMND");
        jpn_ThongTinCaNhan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 100, 38));

        jTF_SoCMND_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_SoCMND_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_SoCMND_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_SoCMND_pn_ThongTinCaNhan.setText("001672038391");
        jTF_SoCMND_pn_ThongTinCaNhan.setBorder(null);
        jTF_SoCMND_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTF_SoCMND_pn_ThongTinCaNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_SoCMND_pn_ThongTinCaNhanKeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTF_SoCMND_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 200, 30));

        jLb_Error_SoCMND.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_SoCMND.setText("*Số CMND không hợp lệ");
        jpn_ThongTinCaNhan.add(jLb_Error_SoCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, 30));
        jpn_ThongTinCaNhan.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, -1));

        jpn_QuanLySanPham.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLySanPham.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jpn_QuanLySanPham.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_QuanLySanPham.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("QUẢN LÝ SẢN PHẨM");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_QuanLySanPham.add(jLabel17);
        jLabel17.setBounds(30, 0, 1040, 100);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Roboto Lt", 0, 20)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 120, 120));
        jPanel6.setLayout(null);

        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.setBackground(new java.awt.Color(0, 90, 90));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã loài vật nuôi", "Mã giống vật nuôi", "Mã vật nuôi", "Đơn giá"
            }
        ));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.setToolTipText("");
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.setGridColor(new java.awt.Color(255, 255, 255));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.setRowHeight(20);
        jScrollPane1.setViewportView(table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP);
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.getTableHeader().setBackground(new java.awt.Color(0, 60, 60));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP.getTableHeader().setFont(new java.awt.Font("Roboto", 1, 16));

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1005, 210);

        jTabbedPane2.addTab("Bảng vật nuôi", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 120, 120));
        jPanel7.setLayout(null);

        table_BangSP_pn_BangSP_pn_QLSP.setBackground(new java.awt.Color(0, 90, 90));
        table_BangSP_pn_BangSP_pn_QLSP.setFont(new java.awt.Font("Roboto Lt", 0, 16)); // NOI18N
        table_BangSP_pn_BangSP_pn_QLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã loại sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng tồn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_BangSP_pn_BangSP_pn_QLSP.setGridColor(new java.awt.Color(255, 255, 255));
        table_BangSP_pn_BangSP_pn_QLSP.setRowHeight(20);
        jScrollPane2.setViewportView(table_BangSP_pn_BangSP_pn_QLSP);
        table_BangSP_pn_BangSP_pn_QLSP.getTableHeader().setBackground(new java.awt.Color(0, 60, 60));
        table_BangSP_pn_BangSP_pn_QLSP.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        table_BangSP_pn_BangSP_pn_QLSP.getTableHeader().setFont(new java.awt.Font("Roboto", 1, 16));

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 1005, 210);

        jTabbedPane2.addTab("Bảng sản phẩm", jPanel7);

        jpn_QuanLySanPham.add(jTabbedPane2);
        jTabbedPane2.setBounds(30, 400, 1010, 240);
        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane4.setToolTipText("");
        jTabbedPane4.setFont(new java.awt.Font("Roboto Lt", 0, 20)); // NOI18N

        jpn_ThemSanPham_QLSP.setBackground(new java.awt.Color(0, 64, 80));
        jpn_ThemSanPham_QLSP.setForeground(new java.awt.Color(0, 90, 90));
        jpn_ThemSanPham_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jpn_ThemSanPham_QLSP.setLayout(null);

        cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giống vật nuôi" }));
        jpn_ThemSanPham_QLSP.add(cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP);
        cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP.setBounds(270, 30, 190, 30);

        cmbx_LoaiSP_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiSP_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiSP_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiSP_pn_ThemSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm" }));
        jpn_ThemSanPham_QLSP.add(cmbx_LoaiSP_pn_ThemSP_pn_QLSP);
        cmbx_LoaiSP_pn_ThemSP_pn_QLSP.setBounds(30, 80, 190, 30);

        cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loài vật nuôi" }));
        jpn_ThemSanPham_QLSP.add(cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP);
        cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP.setBounds(30, 30, 190, 30);

        tf_GiaVatNuoi_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_GiaVatNuoi_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_GiaVatNuoi_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_GiaVatNuoi_pn_ThemSP_pn_QLSP.setText("Đơn giá");
        jpn_ThemSanPham_QLSP.add(tf_GiaVatNuoi_pn_ThemSP_pn_QLSP);
        tf_GiaVatNuoi_pn_ThemSP_pn_QLSP.setBounds(780, 30, 190, 30);

        tf_GiaSP_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_GiaSP_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_GiaSP_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_GiaSP_pn_ThemSP_pn_QLSP.setText("Đơn giá");
        tf_GiaSP_pn_ThemSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_GiaSP_pn_ThemSP_pn_QLSPActionPerformed(evt);
            }
        });
        jpn_ThemSanPham_QLSP.add(tf_GiaSP_pn_ThemSP_pn_QLSP);
        tf_GiaSP_pn_ThemSP_pn_QLSP.setBounds(780, 80, 190, 30);

        tf_MaVatNuoi_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_MaVatNuoi_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_MaVatNuoi_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_MaVatNuoi_pn_ThemSP_pn_QLSP.setText("Mã vật nuôi");
        jpn_ThemSanPham_QLSP.add(tf_MaVatNuoi_pn_ThemSP_pn_QLSP);
        tf_MaVatNuoi_pn_ThemSP_pn_QLSP.setBounds(520, 30, 190, 30);

        tf_MaSP_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_MaSP_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_MaSP_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_MaSP_pn_ThemSP_pn_QLSP.setText("Mã sản phẩm");
        jpn_ThemSanPham_QLSP.add(tf_MaSP_pn_ThemSP_pn_QLSP);
        tf_MaSP_pn_ThemSP_pn_QLSP.setBounds(270, 80, 190, 30);

        tf_TenSP_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_TenSP_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_TenSP_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_TenSP_pn_ThemSP_pn_QLSP.setText("Tên sản phẩm");
        tf_TenSP_pn_ThemSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TenSP_pn_ThemSP_pn_QLSPActionPerformed(evt);
            }
        });
        jpn_ThemSanPham_QLSP.add(tf_TenSP_pn_ThemSP_pn_QLSP);
        tf_TenSP_pn_ThemSP_pn_QLSP.setBounds(520, 80, 190, 30);

        btn_XacNhan_pn_ThemSP_pn_QLSP.setBackground(new java.awt.Color(0, 120, 215));
        btn_XacNhan_pn_ThemSP_pn_QLSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_XacNhan_pn_ThemSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        btn_XacNhan_pn_ThemSP_pn_QLSP.setText("Xác nhận");
        btn_XacNhan_pn_ThemSP_pn_QLSP.setFocusable(false);
        btn_XacNhan_pn_ThemSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhan_pn_ThemSP_pn_QLSPActionPerformed(evt);
            }
        });
        jpn_ThemSanPham_QLSP.add(btn_XacNhan_pn_ThemSP_pn_QLSP);
        btn_XacNhan_pn_ThemSP_pn_QLSP.setBounds(430, 150, 130, 33);

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jpn_ThemSanPham_QLSP.add(jSeparator9);
        jSeparator9.setBounds(30, 130, 940, 10);

        jTabbedPane4.addTab("Thêm sản phẩm", jpn_ThemSanPham_QLSP);

        jpn_SuaSanPham_QLSP.setBackground(new java.awt.Color(0, 64, 80));
        jpn_SuaSanPham_QLSP.setLayout(null);

        cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loài vật nuôi" }));
        jpn_SuaSanPham_QLSP.add(cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP);
        cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP.setBounds(30, 30, 190, 30);

        tf_TenSP_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_TenSP_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_TenSP_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_TenSP_pn_SuaSP_pn_QLSP.setText("Tên sản phẩm");
        tf_TenSP_pn_SuaSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TenSP_pn_SuaSP_pn_QLSPActionPerformed(evt);
            }
        });
        jpn_SuaSanPham_QLSP.add(tf_TenSP_pn_SuaSP_pn_QLSP);
        tf_TenSP_pn_SuaSP_pn_QLSP.setBounds(520, 80, 190, 30);

        tf_GiaVatNuoi_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_GiaVatNuoi_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_GiaVatNuoi_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_GiaVatNuoi_pn_SuaSP_pn_QLSP.setText("Đơn giá");
        jpn_SuaSanPham_QLSP.add(tf_GiaVatNuoi_pn_SuaSP_pn_QLSP);
        tf_GiaVatNuoi_pn_SuaSP_pn_QLSP.setBounds(780, 30, 190, 30);

        tf_GiaSP_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_GiaSP_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_GiaSP_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_GiaSP_pn_SuaSP_pn_QLSP.setText("Đơn giá");
        tf_GiaSP_pn_SuaSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_GiaSP_pn_SuaSP_pn_QLSPActionPerformed(evt);
            }
        });
        jpn_SuaSanPham_QLSP.add(tf_GiaSP_pn_SuaSP_pn_QLSP);
        tf_GiaSP_pn_SuaSP_pn_QLSP.setBounds(780, 80, 190, 30);

        cmbx_LoaiSP_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiSP_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiSP_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiSP_pn_SuaSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm" }));
        cmbx_LoaiSP_pn_SuaSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_LoaiSP_pn_SuaSP_pn_QLSPActionPerformed(evt);
            }
        });
        jpn_SuaSanPham_QLSP.add(cmbx_LoaiSP_pn_SuaSP_pn_QLSP);
        cmbx_LoaiSP_pn_SuaSP_pn_QLSP.setBounds(30, 80, 190, 30);

        cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giống vật nuôi" }));
        jpn_SuaSanPham_QLSP.add(cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP);
        cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP.setBounds(270, 30, 190, 30);

        btn_XacNhan_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 120, 215));
        btn_XacNhan_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_XacNhan_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        btn_XacNhan_pn_SuaSP_pn_QLSP.setText("Xác nhận");
        btn_XacNhan_pn_SuaSP_pn_QLSP.setFocusable(false);
        btn_XacNhan_pn_SuaSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhan_pn_SuaSP_pn_QLSPActionPerformed(evt);
            }
        });
        jpn_SuaSanPham_QLSP.add(btn_XacNhan_pn_SuaSP_pn_QLSP);
        btn_XacNhan_pn_SuaSP_pn_QLSP.setBounds(430, 150, 130, 33);

        tf_MaSP_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_MaSP_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_MaSP_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_MaSP_pn_SuaSP_pn_QLSP.setText("Mã sản phẩm");
        jpn_SuaSanPham_QLSP.add(tf_MaSP_pn_SuaSP_pn_QLSP);
        tf_MaSP_pn_SuaSP_pn_QLSP.setBounds(270, 80, 190, 30);

        tf_MaVatNuoi_pn_SuaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_MaVatNuoi_pn_SuaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_MaVatNuoi_pn_SuaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_MaVatNuoi_pn_SuaSP_pn_QLSP.setText("Mã vật nuôi");
        jpn_SuaSanPham_QLSP.add(tf_MaVatNuoi_pn_SuaSP_pn_QLSP);
        tf_MaVatNuoi_pn_SuaSP_pn_QLSP.setBounds(520, 30, 190, 30);

        jTabbedPane4.addTab("Sửa sản phẩm", jpn_SuaSanPham_QLSP);

        jP_XoaSanPham_QLSP.setBackground(new java.awt.Color(0, 64, 80));
        jP_XoaSanPham_QLSP.setLayout(null);

        cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loài vật nuôi" }));
        cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP.setToolTipText("");
        jP_XoaSanPham_QLSP.add(cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP);
        cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP.setBounds(30, 30, 190, 30);

        cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giống vật nuôi" }));
        cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP.setToolTipText("");
        jP_XoaSanPham_QLSP.add(cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP);
        cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP.setBounds(270, 30, 190, 30);

        btn_XacNhan_pn_XoaSP_pn_QLSP.setBackground(new java.awt.Color(0, 120, 215));
        btn_XacNhan_pn_XoaSP_pn_QLSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_XacNhan_pn_XoaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        btn_XacNhan_pn_XoaSP_pn_QLSP.setText("Xác nhận");
        btn_XacNhan_pn_XoaSP_pn_QLSP.setFocusable(false);
        btn_XacNhan_pn_XoaSP_pn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhan_pn_XoaSP_pn_QLSPActionPerformed(evt);
            }
        });
        jP_XoaSanPham_QLSP.add(btn_XacNhan_pn_XoaSP_pn_QLSP);
        btn_XacNhan_pn_XoaSP_pn_QLSP.setBounds(430, 150, 130, 33);

        cmbx_LoaiSP_pn_XoaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiSP_pn_XoaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiSP_pn_XoaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiSP_pn_XoaSP_pn_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm" }));
        cmbx_LoaiSP_pn_XoaSP_pn_QLSP.setToolTipText("");
        jP_XoaSanPham_QLSP.add(cmbx_LoaiSP_pn_XoaSP_pn_QLSP);
        cmbx_LoaiSP_pn_XoaSP_pn_QLSP.setBounds(30, 80, 190, 30);

        tf_MaSP_pn_XoaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_MaSP_pn_XoaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_MaSP_pn_XoaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_MaSP_pn_XoaSP_pn_QLSP.setText("Mã sản phẩm");
        tf_MaSP_pn_XoaSP_pn_QLSP.setToolTipText("");
        jP_XoaSanPham_QLSP.add(tf_MaSP_pn_XoaSP_pn_QLSP);
        tf_MaSP_pn_XoaSP_pn_QLSP.setBounds(270, 80, 190, 30);

        tf_MaVatNuoi_pn_XoaSP_pn_QLSP.setBackground(new java.awt.Color(0, 60, 60));
        tf_MaVatNuoi_pn_XoaSP_pn_QLSP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tf_MaVatNuoi_pn_XoaSP_pn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        tf_MaVatNuoi_pn_XoaSP_pn_QLSP.setText("Mã vật nuôi");
        tf_MaVatNuoi_pn_XoaSP_pn_QLSP.setToolTipText("");
        jP_XoaSanPham_QLSP.add(tf_MaVatNuoi_pn_XoaSP_pn_QLSP);
        tf_MaVatNuoi_pn_XoaSP_pn_QLSP.setBounds(520, 30, 190, 30);

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jP_XoaSanPham_QLSP.add(jSeparator11);
        jSeparator11.setBounds(30, 130, 940, 10);

        jTabbedPane4.addTab("Xóa sản phẩm", jP_XoaSanPham_QLSP);

        jpn_QuanLySanPham.add(jTabbedPane4);
        jTabbedPane4.setBounds(30, 120, 1010, 240);

        jpn_QuanLyKho.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLyKho.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_QuanLyKho.setLayout(null);

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setFont(new java.awt.Font("Roboto Lt", 0, 20)); // NOI18N

        jpn_QuanLyKho_BangVatNuoi.setBackground(new java.awt.Color(0, 90, 90));
        jpn_QuanLyKho_BangVatNuoi.setLayout(null);

        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho.setBackground(new java.awt.Color(0, 90, 90));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho.setForeground(new java.awt.Color(255, 255, 255));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã loài vật nuôi", "Mã giống vật nuôi", "Mã vật nuôi", "Đơn giá"
            }
        ));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho.setToolTipText("");
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho.setGridColor(new java.awt.Color(255, 255, 255));
        table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho.setRowHeight(20);
        jScrollPane3.setViewportView(table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho);

        jpn_QuanLyKho_BangVatNuoi.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 1005, 310);

        tf_SoLuong_pn_BangVatNuoi_pn_QLKho.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jpn_QuanLyKho_BangVatNuoi.add(tf_SoLuong_pn_BangVatNuoi_pn_QLKho);
        tf_SoLuong_pn_BangVatNuoi_pn_QLKho.setBounds(740, 320, 270, 30);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số lượng:");
        jpn_QuanLyKho_BangVatNuoi.add(jLabel8);
        jLabel8.setBounds(640, 320, 100, 30);

        jTabbedPane3.addTab("Bảng vật nuôi", jpn_QuanLyKho_BangVatNuoi);

        jpn_QuanLyKho_BangSanPham.setBackground(new java.awt.Color(0, 90, 90));
        jpn_QuanLyKho_BangSanPham.setLayout(null);

        table_BangSP_pn_BangSP_pn_QLKho.setBackground(new java.awt.Color(0, 90, 90));
        table_BangSP_pn_BangSP_pn_QLKho.setFont(new java.awt.Font("Roboto Lt", 0, 16)); // NOI18N
        table_BangSP_pn_BangSP_pn_QLKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã loại sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá"
            }
        ));
        table_BangSP_pn_BangSP_pn_QLKho.setGridColor(new java.awt.Color(255, 255, 255));
        table_BangSP_pn_BangSP_pn_QLKho.setRowHeight(20);
        jScrollPane4.setViewportView(table_BangSP_pn_BangSP_pn_QLKho);

        jpn_QuanLyKho_BangSanPham.add(jScrollPane4);
        jScrollPane4.setBounds(0, 0, 1005, 310);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Số lượng:");
        jpn_QuanLyKho_BangSanPham.add(jLabel9);
        jLabel9.setBounds(640, 320, 100, 30);

        tf_SoLuong_pn_BangSP_pn_QLKho.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jpn_QuanLyKho_BangSanPham.add(tf_SoLuong_pn_BangSP_pn_QLKho);
        tf_SoLuong_pn_BangSP_pn_QLKho.setBounds(740, 320, 270, 30);

        jTabbedPane3.addTab("Bảng sản phẩm", jpn_QuanLyKho_BangSanPham);

        jpn_QuanLyKho.add(jTabbedPane3);
        jTabbedPane3.setBounds(30, 250, 1010, 400);

        jLabel18.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("QUẢN LÝ KHO");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_QuanLyKho.add(jLabel18);
        jLabel18.setBounds(30, 0, 1040, 100);

        cmbx_LoaiSP_pn_QLKho.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiSP_pn_QLKho.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiSP_pn_QLKho.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiSP_pn_QLKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm" }));
        jpn_QuanLyKho.add(cmbx_LoaiSP_pn_QLKho);
        cmbx_LoaiSP_pn_QLKho.setBounds(30, 190, 190, 30);

        cmbx_LoaiVatNuoi_pn_QLKho.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_LoaiVatNuoi_pn_QLKho.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_LoaiVatNuoi_pn_QLKho.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_LoaiVatNuoi_pn_QLKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loài vật nuôi" }));
        jpn_QuanLyKho.add(cmbx_LoaiVatNuoi_pn_QLKho);
        cmbx_LoaiVatNuoi_pn_QLKho.setBounds(30, 140, 190, 30);

        cmbx_GiongVatNuoi_pn_QLKho.setBackground(new java.awt.Color(0, 60, 60));
        cmbx_GiongVatNuoi_pn_QLKho.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbx_GiongVatNuoi_pn_QLKho.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_GiongVatNuoi_pn_QLKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giống vật nuôi" }));
        jpn_QuanLyKho.add(cmbx_GiongVatNuoi_pn_QLKho);
        cmbx_GiongVatNuoi_pn_QLKho.setBounds(270, 140, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ExitProgram();
    }//GEN-LAST:event_formWindowClosing

    private void btn_QuanLySanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamMouseEntered
        if(bQuanLySanPham == false)
            btn_QuanLySanPham.setBackground(Color.btn_When_Enter);
        btn_QuanLySanPham.setText("QUẢN LÝ SẢN PHẨM");
    }//GEN-LAST:event_btn_QuanLySanPhamMouseEntered

    private void btn_QuanLyKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseEntered
        if(bQuanLyKho == false)
            btn_QuanLyKho.setBackground(Color.btn_When_Enter);
        btn_QuanLyKho.setText("QUẢN LÝ KHO");
    }//GEN-LAST:event_btn_QuanLyKhoMouseEntered

    private void btn_ThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseEntered
        btn_Thoat.setBackground(Color.btn_When_Enter);
        btn_Thoat.setText("THOÁT");
    }//GEN-LAST:event_btn_ThoatMouseEntered

    private void btn_QuanLySanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamMouseExited
        if(bQuanLySanPham==false)
            btn_QuanLySanPham.setBackground(Color.btn_Default);
        btn_QuanLySanPham.setText("");
    }//GEN-LAST:event_btn_QuanLySanPhamMouseExited

    private void btn_QuanLyKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseExited
        if(bQuanLyKho==false)
            btn_QuanLyKho.setBackground(Color.btn_Default);
        btn_QuanLyKho.setText("");
    }//GEN-LAST:event_btn_QuanLyKhoMouseExited

    private void btn_ThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseExited
        btn_Thoat.setBackground(Color.btn_Default);
        btn_Thoat.setText("");
    }//GEN-LAST:event_btn_ThoatMouseExited

    private void btn_ThongTinCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseEntered
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(Color.btn_When_Enter);
        btn_ThongTinCaNhan.setText("THÔNG TIN CÁ NHÂN");
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseEntered

    private void btn_ThongTinCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseExited
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(Color.btn_Default);
        btn_ThongTinCaNhan.setText("");
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseExited

    private void btn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_ThongTinCaNhan.setBackground(Color.btn_When_Click);
        ThongTinCaNhan_SetAllThingDefault();
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseClicked

    private void btn_QuanLySanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLySanPham.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLySanPham = true;
        SetAllPanelDissapear();
        jpn_QuanLySanPham.setVisible(true);
    }//GEN-LAST:event_btn_QuanLySanPhamMouseClicked

    private void btn_QuanLyKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLyKho.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLyKho = true;
        SetAllPanelDissapear();
        jpn_QuanLyKho.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyKhoMouseClicked

    private void btn_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongTinCaNhanActionPerformed

    private void jTF_DienThoai_pn_ThongTinCaNhanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_DienThoai_pn_ThongTinCaNhanKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))|| vchar == KeyEvent.VK_BACKSPACE || vchar == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_jTF_DienThoai_pn_ThongTinCaNhanKeyTyped

    private void jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked
        // Nếu Xác Nhận Thông Tin Thành Công
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(false);
        ThongTinCaNhan_SetAllTextFieldDisable();
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(true);
        // Cập nhật lại class và gửi thông tin thay đổi về database
    }//GEN-LAST:event_jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked

    private void jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked
        is_ChinhSua_ThongTinCaNhan = true;
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(false);
        ThongTinCaNhan_SetAllTextFieldEnable();
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(true);
    }//GEN-LAST:event_jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked

    private void jTF_SoCMND_pn_ThongTinCaNhanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_SoCMND_pn_ThongTinCaNhanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SoCMND_pn_ThongTinCaNhanKeyTyped

    private void tf_GiaSP_pn_ThemSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_GiaSP_pn_ThemSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_GiaSP_pn_ThemSP_pn_QLSPActionPerformed

    private void tf_TenSP_pn_ThemSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TenSP_pn_ThemSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TenSP_pn_ThemSP_pn_QLSPActionPerformed

    private void btn_XacNhan_pn_ThemSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhan_pn_ThemSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XacNhan_pn_ThemSP_pn_QLSPActionPerformed

    private void tf_TenSP_pn_SuaSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TenSP_pn_SuaSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TenSP_pn_SuaSP_pn_QLSPActionPerformed

    private void tf_GiaSP_pn_SuaSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_GiaSP_pn_SuaSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_GiaSP_pn_SuaSP_pn_QLSPActionPerformed

    private void btn_XacNhan_pn_SuaSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhan_pn_SuaSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XacNhan_pn_SuaSP_pn_QLSPActionPerformed

    private void btn_XacNhan_pn_XoaSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhan_pn_XoaSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XacNhan_pn_XoaSP_pn_QLSPActionPerformed

    private void cmbx_LoaiSP_pn_SuaSP_pn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_LoaiSP_pn_SuaSP_pn_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx_LoaiSP_pn_SuaSP_pn_QLSPActionPerformed
    
    void ThongTinCaNhan_SetAllTextFieldDisable(){
        ThongTinCaNhan_SetAllTextField(false);
        ThongTinCaNhan_SetAllTextFieldColor(Color.tf_Disable_Edited);
    }
    
    void ThongTinCaNhan_SetAllThingDefault(){
        /*
        Đổ lại dữ liệu trong class
        */
        ThongTinCaNhan_SetAllTextFieldDisable();
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(true);
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(false);
    }
    void ThongTinCaNhan_SetAllTextFieldEnable(){
        ThongTinCaNhan_SetAllTextField(true);
        ThongTinCaNhan_SetAllTextFieldColor(Color.tf_Enable_Edited);
    }
        void ThongTinCaNhan_SetAllTextFieldColor(java.awt.Color jColor){
        jTF_DiaChi_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_DienThoai_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_Hoten_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_SoCMND_pn_ThongTinCaNhan.setBackground(jColor);
    }    
        
    void ThongTinCaNhan_SetAllTextField(boolean x){
        jTF_DiaChi_pn_ThongTinCaNhan.setEnabled(x);
        jTF_DienThoai_pn_ThongTinCaNhan.setEnabled(x);
        jTF_Hoten_pn_ThongTinCaNhan.setEnabled(x);
        jTF_SoCMND_pn_ThongTinCaNhan.setEnabled(x);
        jCB_GioiTinh_pn_ThongTinCaNhan.setEnabled(x);
        jDC_NgaySinh_pn_ThongTinCaNhan.setEnabled(x);
    }    
    void SetColorAllButton(java.awt.Color jColor ){
        btn_ThongTinCaNhan.setBackground(jColor);
        btn_QuanLyKho.setBackground(jColor);
        btn_QuanLySanPham.setBackground(jColor);
        btn_Thoat.setBackground(jColor);
    }
    
    void SetFalseAllButton(){
        bThongTinCaNhan = false;
        bQuanLySanPham = false;
        bQuanLyKho = false;
    }
    void SetAllPanelDissapear(){
        jpn_QuanLyKho.setVisible(false);
        jpn_QuanLySanPham.setVisible(false);
        jpn_ThongTinCaNhan.setVisible(false);
    }
    void ExitProgram(){
        int output = JOptionPane.showConfirmDialog(this,"Bạn có thật sự muốn thoát không ?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(output==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else
            return;
    }
    /**
     * @param args the command line arguments
     */
    
    public class FixedStateButtonModel extends DefaultButtonModel    {

        @Override
        public boolean isPressed() {
            return false;
        }

        @Override
        public boolean isRollover() {
            return false;
        }

        @Override
        public void setRollover(boolean b) {
            //NOOP
        }

    }
    
    public static void mmmain(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFNhanVienKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_QuanLyKho;
    private javax.swing.JButton btn_QuanLySanPham;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_ThongTinCaNhan;
    private javax.swing.JButton btn_XacNhan_pn_SuaSP_pn_QLSP;
    private javax.swing.JButton btn_XacNhan_pn_ThemSP_pn_QLSP;
    private javax.swing.JButton btn_XacNhan_pn_XoaSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_GiongVatNuoi_pn_QLKho;
    private javax.swing.JComboBox<String> cmbx_GiongVatNuoi_pn_SuaSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_GiongVatNuoi_pn_ThemSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_GiongVatNuoi_pn_XoaSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_LoaiSP_pn_QLKho;
    private javax.swing.JComboBox<String> cmbx_LoaiSP_pn_SuaSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_LoaiSP_pn_ThemSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_LoaiSP_pn_XoaSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_LoaiVatNuoi_pn_QLKho;
    private javax.swing.JComboBox<String> cmbx_LoaiVatNuoi_pn_SuaSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_LoaiVatNuoi_pn_ThemSP_pn_QLSP;
    private javax.swing.JComboBox<String> cmbx_LoaiVatNuoi_pn_XoaSP_pn_QLSP;
    private javax.swing.JButton jBtn_ChinhSua_pn_ThongTinCaNhan;
    private javax.swing.JButton jBtn_XacNhan_pn_ThongTinCaNhan;
    private javax.swing.JComboBox<String> jCB_GioiTinh_pn_ThongTinCaNhan;
    private com.toedter.calendar.JDateChooser jDC_NgaySinh_pn_ThongTinCaNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLb_Error_HoTen;
    private javax.swing.JLabel jLb_Error_SDT;
    private javax.swing.JLabel jLb_Error_SoCMND;
    private javax.swing.JPanel jP_XoaSanPham_QLSP;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTF_DiaChi_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_DienThoai_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_Hoten_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_SoCMND_pn_ThongTinCaNhan;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel jpn_QuanLyKho;
    private javax.swing.JPanel jpn_QuanLyKho_BangSanPham;
    private javax.swing.JPanel jpn_QuanLyKho_BangVatNuoi;
    private javax.swing.JPanel jpn_QuanLySanPham;
    private javax.swing.JPanel jpn_SuaSanPham_QLSP;
    private javax.swing.JPanel jpn_ThemSanPham_QLSP;
    private javax.swing.JPanel jpn_ThongTinCaNhan;
    private javax.swing.JTable table_BangSP_pn_BangSP_pn_QLKho;
    private javax.swing.JTable table_BangSP_pn_BangSP_pn_QLSP;
    private javax.swing.JTable table_BangVatNuoi_pn_BangVatNuoi_pn_QLKho;
    private javax.swing.JTable table_BangVatNuoi_pn_BangVatNuoi_pn_QLSP;
    private javax.swing.JTextField tf_GiaSP_pn_SuaSP_pn_QLSP;
    private javax.swing.JTextField tf_GiaSP_pn_ThemSP_pn_QLSP;
    private javax.swing.JTextField tf_GiaVatNuoi_pn_SuaSP_pn_QLSP;
    private javax.swing.JTextField tf_GiaVatNuoi_pn_ThemSP_pn_QLSP;
    private javax.swing.JTextField tf_MaSP_pn_SuaSP_pn_QLSP;
    private javax.swing.JTextField tf_MaSP_pn_ThemSP_pn_QLSP;
    private javax.swing.JTextField tf_MaSP_pn_XoaSP_pn_QLSP;
    private javax.swing.JTextField tf_MaVatNuoi_pn_SuaSP_pn_QLSP;
    private javax.swing.JTextField tf_MaVatNuoi_pn_ThemSP_pn_QLSP;
    private javax.swing.JTextField tf_MaVatNuoi_pn_XoaSP_pn_QLSP;
    private javax.swing.JTextField tf_SoLuong_pn_BangSP_pn_QLKho;
    private javax.swing.JTextField tf_SoLuong_pn_BangVatNuoi_pn_QLKho;
    private javax.swing.JTextField tf_TenSP_pn_SuaSP_pn_QLSP;
    private javax.swing.JTextField tf_TenSP_pn_ThemSP_pn_QLSP;
    // End of variables declaration//GEN-END:variables
}
