/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameMain;
import Data.Data;
import static JFrameMain.jF_ChuCuaHang.Color;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.DefaultButtonModel;

/**
 *
 * @author voanh
 */
public class jFNhanVienBanHang extends javax.swing.JFrame {
    static String id="";
    static String maChucVu;
    static String mk="";

    static String errorText = "Tên đăng nhập hoặc mật khẩu không hợp lệ !";
    static Class_Color Color = new Class_Color();
    
    boolean bThongTinCaNhan = false;
    boolean bQuanLyKhachHang = false;
    boolean bQuanLyHoaDon = false;
    boolean bQuanLyThanhToan = false;
    boolean bQuanLySanPhamKho = false;
    boolean is_ChinhSua_ThongTinCaNhan = false;
    
    /**
     * Creates new form jFMain
     */
    public jFNhanVienBanHang() {
        
         Data d = new Data();
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        
        initComponents();
         
        setLocationRelativeTo(null);
        this.setVisible(true);
        
        
        
        btn_ThongTinCaNhan.setModel(new FixedStateButtonModel());
        btn_QuanLyKhachHang.setModel(new FixedStateButtonModel());
        btn_QuanLyHoaDon.setModel(new FixedStateButtonModel());
        btn_QuanLySanPhamKho.setModel(new FixedStateButtonModel());
        btn_Thoat.setModel(new FixedStateButtonModel());
        btn_QuanLyThanhToan.setModel(new FixedStateButtonModel());
        
        
        //
        SetColorAllButton(Color.btn_Default);
        btn_ThongTinCaNhan.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
        //
        ThongTinCaNhan_SetAllTextFieldDisable();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Thoat = new javax.swing.JButton();
        btn_QuanLyKhachHang = new javax.swing.JButton();
        btn_QuanLyHoaDon = new javax.swing.JButton();
        btn_QuanLySanPhamKho = new javax.swing.JButton();
        btn_QuanLyThanhToan = new javax.swing.JButton();
        btn_ThongTinCaNhan = new javax.swing.JButton();
        jpn_ThongTinCaNhan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTF_DiaChi_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jCB_GioiTinh_pn_ThongTinCaNhan = new javax.swing.JComboBox<>();
        jDC_NgaySinh_pn_ThongTinCaNhan = new com.toedter.calendar.JDateChooser();
        jTF_Hoten_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jTF_DienThoai_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jBtn_XacNhan_pn_ThongTinCaNhan = new javax.swing.JButton();
        jBtn_ChinhSua_pn_ThongTinCaNhan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLb_Error_SDT = new javax.swing.JLabel();
        jLb_Error_HoTen = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTF_SoCMND_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jLb_Error_SoCMND = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jpn_QuanLyKhachHang = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTF_MANV = new javax.swing.JTextField();
        jTF_HoTen = new javax.swing.JTextField();
        jTF_DiaChi = new javax.swing.JTextField();
        jTF_SDT = new javax.swing.JTextField();
        jCB_GioiTinh = new javax.swing.JComboBox<>();
        jDC_NgaySinh = new com.toedter.calendar.JDateChooser();
        jTF_SOCMND = new javax.swing.JTextField();
        btn_QuanLyKho2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btn_QuanLyKho3 = new javax.swing.JButton();
        btn_QuanLyKho1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTB_ThongTin = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTF_MANV1 = new javax.swing.JTextField();
        jTF_HoTen1 = new javax.swing.JTextField();
        jTF_DiaChi1 = new javax.swing.JTextField();
        jTF_SDT1 = new javax.swing.JTextField();
        jCB_GioiTinh1 = new javax.swing.JComboBox<>();
        jDC_NgaySinh1 = new com.toedter.calendar.JDateChooser();
        jTF_SOCMND1 = new javax.swing.JTextField();
        btn_QuanLyKho4 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jpn_QuanLySanPhamKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpn_QuanLyHoaDon = new javax.swing.JPanel();
        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_time_Time = new com.toedter.calendar.JDateChooser();
        JNhanVienBanHang_XemHoaDon_btn_TimKiem = new javax.swing.JButton();
        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon = new javax.swing.JTable();
        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_Tong = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jpn_QuanLyThanhToan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImages(null);
        setLocationByPlatform(true);
        setName("fLogin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cat-profile-75.png"))); // NOI18N
        jLabel2.setText("PETS STORE");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chào  TUANKYOU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 64, 80));

        btn_Thoat.setBackground(new java.awt.Color(32, 78, 80));
        btn_Thoat.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Exit_Sign_48px.png"))); // NOI18N
        btn_Thoat.setBorder(null);
        btn_Thoat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Thoat.setFocusable(false);
        btn_Thoat.setName(""); // NOI18N
        btn_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseExited(evt);
            }
        });

        btn_QuanLyKhachHang.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLyKhachHang.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLyKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Staff_48px_1.png"))); // NOI18N
        btn_QuanLyKhachHang.setBorder(null);
        btn_QuanLyKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKhachHang.setFocusable(false);
        btn_QuanLyKhachHang.setName(""); // NOI18N
        btn_QuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhachHangMouseExited(evt);
            }
        });

        btn_QuanLyHoaDon.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLyHoaDon.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Paper_Money_50px.png"))); // NOI18N
        btn_QuanLyHoaDon.setBorder(null);
        btn_QuanLyHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyHoaDon.setFocusable(false);
        btn_QuanLyHoaDon.setName(""); // NOI18N
        btn_QuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyHoaDonMouseExited(evt);
            }
        });

        btn_QuanLySanPhamKho.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLySanPhamKho.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLySanPhamKho.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLySanPhamKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_House_50px.png"))); // NOI18N
        btn_QuanLySanPhamKho.setBorder(null);
        btn_QuanLySanPhamKho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLySanPhamKho.setFocusable(false);
        btn_QuanLySanPhamKho.setName(""); // NOI18N
        btn_QuanLySanPhamKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamKhoMouseExited(evt);
            }
        });

        btn_QuanLyThanhToan.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLyThanhToan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLyThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Bill_64px.png"))); // NOI18N
        btn_QuanLyThanhToan.setBorder(null);
        btn_QuanLyThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyThanhToan.setFocusable(false);
        btn_QuanLyThanhToan.setName(""); // NOI18N
        btn_QuanLyThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyThanhToanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyThanhToanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyThanhToanMouseExited(evt);
            }
        });

        btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 64, 80));
        btn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Personal_Trainer_50px.png"))); // NOI18N
        btn_ThongTinCaNhan.setBorder(null);
        btn_ThongTinCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ThongTinCaNhan.setFocusable(false);
        btn_ThongTinCaNhan.setName(""); // NOI18N
        btn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseExited(evt);
            }
        });
        btn_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 64, 80));
        jpn_ThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_ThongTinCaNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("THÔNG TIN CÁ NHÂN");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_ThongTinCaNhan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1040, 100));

        jLabel3.setBackground(new java.awt.Color(0, 96, 100));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Địa Chỉ");
        jpn_ThongTinCaNhan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 30));

        jLabel4.setBackground(new java.awt.Color(0, 96, 100));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ Tên ");
        jpn_ThongTinCaNhan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 30));

        jLabel5.setBackground(new java.awt.Color(0, 96, 100));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới Tính");
        jpn_ThongTinCaNhan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 30));

        jLabel6.setBackground(new java.awt.Color(0, 96, 100));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Sinh");
        jpn_ThongTinCaNhan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 30));

        jLabel7.setBackground(new java.awt.Color(0, 96, 100));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Điện Thoại");
        jpn_ThongTinCaNhan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 38));

        jTF_DiaChi_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_DiaChi_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_DiaChi_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_DiaChi_pn_ThongTinCaNhan.setText("Củ Chi, Việt Nam");
        jTF_DiaChi_pn_ThongTinCaNhan.setBorder(null);
        jTF_DiaChi_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jpn_ThongTinCaNhan.add(jTF_DiaChi_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 374, 30));

        jCB_GioiTinh_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jCB_GioiTinh_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jCB_GioiTinh_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jCB_GioiTinh_pn_ThongTinCaNhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jCB_GioiTinh_pn_ThongTinCaNhan.setBorder(null);
        jpn_ThongTinCaNhan.add(jCB_GioiTinh_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 30));

        jDC_NgaySinh_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 0, 0));
        jDC_NgaySinh_pn_ThongTinCaNhan.setDateFormatString("dd/MM/yyyy");
        jpn_ThongTinCaNhan.add(jDC_NgaySinh_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 30));

        jTF_Hoten_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_Hoten_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_Hoten_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_Hoten_pn_ThongTinCaNhan.setText("Võ Anh Tuấn");
        jTF_Hoten_pn_ThongTinCaNhan.setBorder(null);
        jTF_Hoten_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jpn_ThongTinCaNhan.add(jTF_Hoten_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 30));

        jTF_DienThoai_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_DienThoai_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_DienThoai_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_DienThoai_pn_ThongTinCaNhan.setText("001672038391");
        jTF_DienThoai_pn_ThongTinCaNhan.setBorder(null);
        jTF_DienThoai_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTF_DienThoai_pn_ThongTinCaNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_DienThoai_pn_ThongTinCaNhanKeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTF_DienThoai_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 200, 30));

        jBtn_XacNhan_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        jBtn_XacNhan_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_XacNhan_pn_ThongTinCaNhan.setText("Xác Nhận");
        jBtn_XacNhan_pn_ThongTinCaNhan.setBorder(null);
        jBtn_XacNhan_pn_ThongTinCaNhan.setFocusable(false);
        jBtn_XacNhan_pn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jBtn_XacNhan_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 125, 47));

        jBtn_ChinhSua_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        jBtn_ChinhSua_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_ChinhSua_pn_ThongTinCaNhan.setText("Chỉnh Sửa");
        jBtn_ChinhSua_pn_ThongTinCaNhan.setBorder(null);
        jBtn_ChinhSua_pn_ThongTinCaNhan.setFocusable(false);
        jBtn_ChinhSua_pn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jBtn_ChinhSua_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 125, 47));
        jpn_ThongTinCaNhan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 374, -1));

        jLb_Error_SDT.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_SDT.setText("*Số điện thoại không hợp lệ");
        jpn_ThongTinCaNhan.add(jLb_Error_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, 30));

        jLb_Error_HoTen.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_HoTen.setText("*Tên đăng nhập không chứa ký tự đặt biệt");
        jpn_ThongTinCaNhan.add(jLb_Error_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, 30));

        jLabel15.setBackground(new java.awt.Color(0, 96, 100));
        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Số CMND");
        jpn_ThongTinCaNhan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 100, 38));

        jTF_SoCMND_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_SoCMND_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_SoCMND_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_SoCMND_pn_ThongTinCaNhan.setText("001672038391");
        jTF_SoCMND_pn_ThongTinCaNhan.setBorder(null);
        jTF_SoCMND_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTF_SoCMND_pn_ThongTinCaNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_SoCMND_pn_ThongTinCaNhanKeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTF_SoCMND_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 200, 30));

        jLb_Error_SoCMND.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_SoCMND.setText("*Số CMND không hợp lệ");
        jpn_ThongTinCaNhan.add(jLb_Error_SoCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, 30));
        jpn_ThongTinCaNhan.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, -1));

        jpn_QuanLyKhachHang.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLyKhachHang.setPreferredSize(new java.awt.Dimension(1070, 720));

        jPanel6.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 120, 120));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Họ Tên");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 119, 30));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Giới Tính");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 119, 30));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ngày Sinh");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 119, 30));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Số Điện Thoại");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 119, 30));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Địa Chỉ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 119, 30));

        jTF_MANV.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_MANV.setToolTipText("Sundep trai");
        jTF_MANV.setBorder(null);
        jTF_MANV.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jTF_MANV.setName(""); // NOI18N
        jTF_MANV.setSelectionColor(new java.awt.Color(255, 51, 153));
        jPanel1.add(jTF_MANV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, 30));

        jTF_HoTen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_HoTen.setBorder(null);
        jTF_HoTen.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, 30));

        jTF_DiaChi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_DiaChi.setBorder(null);
        jTF_DiaChi.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 190, 30));

        jTF_SDT.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SDT.setBorder(null);
        jTF_SDT.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 190, 30));

        jCB_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "null" }));
        jCB_GioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_GioiTinhActionPerformed(evt);
            }
        });
        jPanel1.add(jCB_GioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 190, 30));

        jDC_NgaySinh.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDC_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, 30));

        jTF_SOCMND.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SOCMND.setBorder(null);
        jTF_SOCMND.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTF_SOCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 210, 30));

        btn_QuanLyKho2.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho2.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho2.setText("Xác Nhận");
        btn_QuanLyKho2.setBorder(null);
        btn_QuanLyKho2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho2.setFocusable(false);
        btn_QuanLyKho2.setName(""); // NOI18N
        jPanel1.add(btn_QuanLyKho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 90, 30));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Mã Khách Hàng");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 119, 30));

        btn_QuanLyKho3.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho3.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho3.setText("Sửa ");
        btn_QuanLyKho3.setBorder(null);
        btn_QuanLyKho3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho3.setFocusable(false);
        btn_QuanLyKho3.setName(""); // NOI18N
        jPanel1.add(btn_QuanLyKho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 90, 30));

        btn_QuanLyKho1.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho1.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho1.setText("Xóa");
        btn_QuanLyKho1.setBorder(null);
        btn_QuanLyKho1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho1.setFocusable(false);
        btn_QuanLyKho1.setName(""); // NOI18N
        jPanel1.add(btn_QuanLyKho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 90, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Số CMND");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 70, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, 10));

        jPanel6.add(jPanel1);
        jPanel1.setBounds(240, 0, 787, 460);

        jButton3.setText("Tìm kiếm");

        jLabel18.setText("Tìm kiếm khách hàng theo Mã KH");
        jLabel18.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTextField6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(33, 33, 33))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
        );

        jPanel6.add(jPanel4);
        jPanel4.setBounds(10, 10, 210, 107);

        jTB_ThongTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTB_ThongTin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTB_ThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KH001", "Nguyễn Văn Tèo"},
                {"KH002", "Trần Thị Tí"},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null},
                {"", null}
            },
            new String [] {
                "MÃ KH", "Họ Tên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTB_ThongTin.setGridColor(new java.awt.Color(255, 255, 255));
        jTB_ThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTB_ThongTinMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTB_ThongTinMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTB_ThongTin);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 210, 320);

        jTabbedPane1.addTab("Thông Tin Khách Hàng", new javax.swing.ImageIcon(getClass().getResource("/Image/Cat Profile_25px.png")), jPanel6); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0, 120, 120));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Họ Tên");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 119, 30));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Giới Tính");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 119, 30));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Ngày Sinh");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 119, 30));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Số Điện Thoại");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 119, 30));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Địa Chỉ");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 119, 30));

        jTF_MANV1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_MANV1.setToolTipText("Sundep trai");
        jTF_MANV1.setBorder(null);
        jTF_MANV1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jTF_MANV1.setName(""); // NOI18N
        jTF_MANV1.setSelectionColor(new java.awt.Color(255, 51, 153));
        jPanel5.add(jTF_MANV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 190, 30));

        jTF_HoTen1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_HoTen1.setBorder(null);
        jTF_HoTen1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_HoTen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, 30));

        jTF_DiaChi1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_DiaChi1.setBorder(null);
        jTF_DiaChi1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_DiaChi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 190, 30));

        jTF_SDT1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SDT1.setBorder(null);
        jTF_SDT1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_SDT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 190, 30));

        jCB_GioiTinh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "null" }));
        jPanel5.add(jCB_GioiTinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 190, 30));

        jDC_NgaySinh1.setDateFormatString("dd/MM/yyyy");
        jPanel5.add(jDC_NgaySinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 190, 30));

        jTF_SOCMND1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTF_SOCMND1.setBorder(null);
        jTF_SOCMND1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jPanel5.add(jTF_SOCMND1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 220, 30));

        btn_QuanLyKho4.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKho4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKho4.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho4.setText("Xác Nhận");
        btn_QuanLyKho4.setBorder(null);
        btn_QuanLyKho4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho4.setFocusable(false);
        btn_QuanLyKho4.setName(""); // NOI18N
        jPanel5.add(btn_QuanLyKho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 90, 30));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Mã Nhân Viên");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 119, 30));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Số CMND");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 70, 30));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 20, 310));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 250, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1015, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Thêm Khách Hàng", new javax.swing.ImageIcon(getClass().getResource("/Image/Cat Profile_25px.png")), jPanel7); // NOI18N

        javax.swing.GroupLayout jpn_QuanLyKhachHangLayout = new javax.swing.GroupLayout(jpn_QuanLyKhachHang);
        jpn_QuanLyKhachHang.setLayout(jpn_QuanLyKhachHangLayout);
        jpn_QuanLyKhachHangLayout.setHorizontalGroup(
            jpn_QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(jpn_QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpn_QuanLyKhachHangLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpn_QuanLyKhachHangLayout.setVerticalGroup(
            jpn_QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(jpn_QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpn_QuanLyKhachHangLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpn_QuanLySanPhamKho.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLySanPhamKho.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel10.setText("Quản Lý Sản Phẩm / Kho");

        javax.swing.GroupLayout jpn_QuanLySanPhamKhoLayout = new javax.swing.GroupLayout(jpn_QuanLySanPhamKho);
        jpn_QuanLySanPhamKho.setLayout(jpn_QuanLySanPhamKhoLayout);
        jpn_QuanLySanPhamKhoLayout.setHorizontalGroup(
            jpn_QuanLySanPhamKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLySanPhamKhoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLySanPhamKhoLayout.setVerticalGroup(
            jpn_QuanLySanPhamKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLySanPhamKhoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        jpn_QuanLyHoaDon.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLyHoaDon.setPreferredSize(new java.awt.Dimension(1070, 720));

        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon.setText("TRA CỨU HÓA ĐƠN");

        JNhanVienBanHang_XemHoaDon_time_Time.setDateFormatString("d MMMM, yyyy");
        JNhanVienBanHang_XemHoaDon_time_Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JNhanVienBanHang_XemHoaDon_btn_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_btn_TimKiem.setText("Tìm kiếm");
        JNhanVienBanHang_XemHoaDon_btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed(evt);
            }
        });

        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon.setText("Bảng Hóa Đơn");

        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setBackground(new java.awt.Color(0, 90, 90));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "NV001", "01/01/2017", "KH002"},
                {"002", "NV003", "01/02/2017", "KH110"},
                {"003", "NV001", "04/02/2017", "KH103"},
                {"004", "NV003", "07/03/2017", "KH106"},
                {"007", "NV004", "08/03/2017", "KH204"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Người lập hóa đơn", "Ngày lập hóa đơn", "Khách hàng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setGridColor(new java.awt.Color(0, 102, 102));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setInheritsPopupMenu(true);
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setRowHeight(20);
        jScrollPane3.setViewportView(JNhanVienBanHang_XemHoaDon_tb_BangHoaDon);

        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setBackground(new java.awt.Color(0, 90, 90));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Loại sản phẩm", "Tên sản phẩm", "Giá", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setGridColor(new java.awt.Color(0, 102, 102));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setMinimumSize(new java.awt.Dimension(60, 480));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setPreferredSize(new java.awt.Dimension(300, 480));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setRowHeight(20);
        jScrollPane1.setViewportView(JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon);

        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien.setText("...................................");

        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien.setText("Tên nhân viên:");

        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang.setText("Tên khách hàng:");

        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang.setText("...................................");

        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon.setText("Bảng Chi Tiết Hóa Đơn");

        JNhanVienBanHang_XemHoaDon_lb_Tong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_Tong.setText("Tổng:");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_QuanLyHoaDonLayout = new javax.swing.GroupLayout(jpn_QuanLyHoaDon);
        jpn_QuanLyHoaDon.setLayout(jpn_QuanLyHoaDonLayout);
        jpn_QuanLyHoaDonLayout.setHorizontalGroup(
            jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 21, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))
                                .addContainerGap())))
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemHoaDon_time_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JNhanVienBanHang_XemHoaDon_btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_QuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JNhanVienBanHang_XemHoaDon_lb_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpn_QuanLyHoaDonLayout.setVerticalGroup(
            jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JNhanVienBanHang_XemHoaDon_lb_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNhanVienBanHang_XemHoaDon_btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JNhanVienBanHang_XemHoaDon_time_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangHoaDon)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon))
                        .addGap(21, 21, 21)
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenNhanVien)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenKhachHang)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang))))
                .addGap(18, 18, 18)
                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNhanVienBanHang_XemHoaDon_lb_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jpn_QuanLyThanhToan.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLyThanhToan.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel11.setText("Quản Lý Thanh Toán");

        javax.swing.GroupLayout jpn_QuanLyThanhToanLayout = new javax.swing.GroupLayout(jpn_QuanLyThanhToan);
        jpn_QuanLyThanhToan.setLayout(jpn_QuanLyThanhToanLayout);
        jpn_QuanLyThanhToanLayout.setHorizontalGroup(
            jpn_QuanLyThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyThanhToanLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLyThanhToanLayout.setVerticalGroup(
            jpn_QuanLyThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyThanhToanLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ExitProgram();
    }//GEN-LAST:event_formWindowClosing

    private void btn_QuanLyKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangMouseEntered
        if(bQuanLyKhachHang == false)
            btn_QuanLyKhachHang.setBackground(Color.btn_When_Enter);
        btn_QuanLyKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");
    }//GEN-LAST:event_btn_QuanLyKhachHangMouseEntered

    private void btn_QuanLyHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonMouseEntered
        if(bQuanLyHoaDon == false)
            btn_QuanLyHoaDon.setBackground(Color.btn_When_Enter);
        btn_QuanLyHoaDon.setText("QUẢN LÝ HÓA ĐƠN");
    }//GEN-LAST:event_btn_QuanLyHoaDonMouseEntered

    private void btn_QuanLyThanhToanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThanhToanMouseEntered
        if(bQuanLyThanhToan == false)
            btn_QuanLyThanhToan.setBackground(Color.btn_When_Enter);
        btn_QuanLyThanhToan.setText("QUẢN LÝ THANH TOÁN");
    }//GEN-LAST:event_btn_QuanLyThanhToanMouseEntered

    private void btn_QuanLySanPhamKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamKhoMouseEntered
        if(bQuanLySanPhamKho==false)
            btn_QuanLySanPhamKho.setBackground(Color.btn_When_Enter);
        btn_QuanLySanPhamKho.setText("QL SẢN PHẨM/KHO");
    }//GEN-LAST:event_btn_QuanLySanPhamKhoMouseEntered

    private void btn_ThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseEntered
        btn_Thoat.setBackground(Color.btn_When_Enter);
        btn_Thoat.setText("THOÁT");
    }//GEN-LAST:event_btn_ThoatMouseEntered

    private void btn_QuanLyKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangMouseExited
        if(bQuanLyKhachHang==false)
            btn_QuanLyKhachHang.setBackground(Color.btn_Default);
        btn_QuanLyKhachHang.setText("");
    }//GEN-LAST:event_btn_QuanLyKhachHangMouseExited

    private void btn_QuanLyHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonMouseExited
        if(bQuanLyHoaDon==false)
            btn_QuanLyHoaDon.setBackground(Color.btn_Default);
        btn_QuanLyHoaDon.setText("");
    }//GEN-LAST:event_btn_QuanLyHoaDonMouseExited

    private void btn_QuanLyThanhToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThanhToanMouseExited
        if(bQuanLyThanhToan==false)
            btn_QuanLyThanhToan.setBackground(Color.btn_Default);
        btn_QuanLyThanhToan.setText("");
    }//GEN-LAST:event_btn_QuanLyThanhToanMouseExited

    private void btn_QuanLySanPhamKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamKhoMouseExited
        if(bQuanLySanPhamKho==false)
            btn_QuanLySanPhamKho.setBackground(Color.btn_Default);
        btn_QuanLySanPhamKho.setText("");
    }//GEN-LAST:event_btn_QuanLySanPhamKhoMouseExited

    private void btn_ThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseExited
        btn_Thoat.setBackground(Color.btn_Default);
        btn_Thoat.setText("");
    }//GEN-LAST:event_btn_ThoatMouseExited

    private void btn_ThongTinCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseEntered
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(Color.btn_When_Enter);
        btn_ThongTinCaNhan.setText("THÔNG TIN CÁ NHÂN");
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseEntered

    private void btn_ThongTinCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseExited
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(Color.btn_Default);
        btn_ThongTinCaNhan.setText("");
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseExited

    private void btn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_ThongTinCaNhan.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseClicked

    private void btn_QuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLyKhachHang.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLyKhachHang = true;
        SetAllPanelDissapear();
        jpn_QuanLyKhachHang.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyKhachHangMouseClicked

    private void btn_QuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLyHoaDon.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLyHoaDon = true;
        SetAllPanelDissapear();
        jpn_QuanLyHoaDon.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyHoaDonMouseClicked

    private void btn_QuanLyThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThanhToanMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLyThanhToan.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLyThanhToan = true;
        SetAllPanelDissapear();
        jpn_QuanLyThanhToan.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyThanhToanMouseClicked

    private void btn_QuanLySanPhamKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamKhoMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLySanPhamKho.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLySanPhamKho = true;
        SetAllPanelDissapear();
        jpn_QuanLySanPhamKho.setVisible(true);
    }//GEN-LAST:event_btn_QuanLySanPhamKhoMouseClicked

    private void btn_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongTinCaNhanActionPerformed

    private void JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTB_ThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTB_ThongTinMouseClicked

       
    }//GEN-LAST:event_jTB_ThongTinMouseClicked

    private void jTB_ThongTinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTB_ThongTinMousePressed
        // TODO add your handling code here:
        //Lấy ra MSNV -> Search trong database -> And thông tin sau khi search vào

    }//GEN-LAST:event_jTB_ThongTinMousePressed

    private void jCB_GioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_GioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_GioiTinhActionPerformed

    private void jTF_DienThoai_pn_ThongTinCaNhanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_DienThoai_pn_ThongTinCaNhanKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))|| vchar == KeyEvent.VK_BACKSPACE || vchar == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_jTF_DienThoai_pn_ThongTinCaNhanKeyTyped

    private void jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked
        // Nếu Xác Nhận Thông Tin Thành Công
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(false);
        ThongTinCaNhan_SetAllTextFieldDisable();
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(true);
        // Cập nhật lại class và gửi thông tin thay đổi về database
    }//GEN-LAST:event_jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked

    private void jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked
        is_ChinhSua_ThongTinCaNhan = true;
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(false);
        ThongTinCaNhan_SetAllTextFieldEnable();
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(true);
    }//GEN-LAST:event_jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked

        void ThongTinCaNhan_SetAllTextFieldDisable(){
        ThongTinCaNhan_SetAllTextField(false);
        ThongTinCaNhan_SetAllTextFieldColor(Color.tf_Disable_Edited);
    }
    
    void ThongTinCaNhan_SetAllTextFieldEnable(){
        ThongTinCaNhan_SetAllTextField(true);
        ThongTinCaNhan_SetAllTextFieldColor(Color.tf_Enable_Edited);
    }
        
    void ThongTinCaNhan_SetAllTextField(boolean x){
        jTF_DiaChi_pn_ThongTinCaNhan.setEnabled(x);
        jTF_DienThoai_pn_ThongTinCaNhan.setEnabled(x);
        jTF_Hoten_pn_ThongTinCaNhan.setEnabled(x);
        jTF_SoCMND_pn_ThongTinCaNhan.setEnabled(x);
        jCB_GioiTinh_pn_ThongTinCaNhan.setEnabled(x);
        jDC_NgaySinh_pn_ThongTinCaNhan.setEnabled(x);
    }
    
    void ThongTinCaNhan_SetAllTextFieldColor(java.awt.Color jColor){
        jTF_DiaChi_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_DienThoai_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_Hoten_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_SoCMND_pn_ThongTinCaNhan.setBackground(jColor);
    }
    private void jTF_SoCMND_pn_ThongTinCaNhanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_SoCMND_pn_ThongTinCaNhanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SoCMND_pn_ThongTinCaNhanKeyTyped
    
    
    void SetColorAllButton(java.awt.Color jColor ){
        btn_ThongTinCaNhan.setBackground(jColor);
        btn_QuanLyHoaDon.setBackground(jColor);
        btn_QuanLyKhachHang.setBackground(jColor);
        btn_QuanLySanPhamKho.setBackground(jColor);
        btn_Thoat.setBackground(jColor);
        btn_QuanLyThanhToan.setBackground(jColor);
    }
    
    void SetFalseAllButton(){
        bThongTinCaNhan = false;
        bQuanLyKhachHang = false;
        bQuanLyHoaDon = false;
        bQuanLyThanhToan = false;
        bQuanLySanPhamKho = false;
    }
    void SetAllPanelDissapear(){
        jpn_QuanLySanPhamKho.setVisible(false);
        jpn_QuanLyKhachHang.setVisible(false);
        jpn_QuanLyHoaDon.setVisible(false);
        jpn_QuanLyThanhToan.setVisible(false);
        jpn_ThongTinCaNhan.setVisible(false);
    }
    void ExitProgram(){
        int output = JOptionPane.showConfirmDialog(this,"Bạn có thật sự muốn thoát không ?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(output==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else
            return;
    }
    /**
     * @param args the command line arguments
     */
    
    public class FixedStateButtonModel extends DefaultButtonModel    {

        @Override
        public boolean isPressed() {
            return false;
        }

        @Override
        public boolean isRollover() {
            return false;
        }

        @Override
        public void setRollover(boolean b) {
            //NOOP
        }

    }
    
    public static void mmmain(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFNhanVienBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JNhanVienBanHang_XemHoaDon_btn_TimKiem;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_BangHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_TenKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_TenNhanVien;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_Tong;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_XemHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien;
    private javax.swing.JTable JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon;
    private javax.swing.JTable JNhanVienBanHang_XemHoaDon_tb_BangHoaDon;
    private com.toedter.calendar.JDateChooser JNhanVienBanHang_XemHoaDon_time_Time;
    private javax.swing.JButton btn_QuanLyHoaDon;
    private javax.swing.JButton btn_QuanLyKhachHang;
    private javax.swing.JButton btn_QuanLyKho1;
    private javax.swing.JButton btn_QuanLyKho2;
    private javax.swing.JButton btn_QuanLyKho3;
    private javax.swing.JButton btn_QuanLyKho4;
    private javax.swing.JButton btn_QuanLySanPhamKho;
    private javax.swing.JButton btn_QuanLyThanhToan;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_ThongTinCaNhan;
    private javax.swing.JButton jBtn_ChinhSua_pn_ThongTinCaNhan;
    private javax.swing.JButton jBtn_XacNhan_pn_ThongTinCaNhan;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCB_GioiTinh;
    private javax.swing.JComboBox<String> jCB_GioiTinh1;
    private javax.swing.JComboBox<String> jCB_GioiTinh_pn_ThongTinCaNhan;
    private com.toedter.calendar.JDateChooser jDC_NgaySinh;
    private com.toedter.calendar.JDateChooser jDC_NgaySinh1;
    private com.toedter.calendar.JDateChooser jDC_NgaySinh_pn_ThongTinCaNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLb_Error_HoTen;
    private javax.swing.JLabel jLb_Error_SDT;
    private javax.swing.JLabel jLb_Error_SoCMND;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTB_ThongTin;
    private javax.swing.JTextField jTF_DiaChi;
    private javax.swing.JTextField jTF_DiaChi1;
    private javax.swing.JTextField jTF_DiaChi_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_DienThoai_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_HoTen;
    private javax.swing.JTextField jTF_HoTen1;
    private javax.swing.JTextField jTF_Hoten_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_MANV;
    private javax.swing.JTextField jTF_MANV1;
    private javax.swing.JTextField jTF_SDT;
    private javax.swing.JTextField jTF_SDT1;
    private javax.swing.JTextField jTF_SOCMND;
    private javax.swing.JTextField jTF_SOCMND1;
    private javax.swing.JTextField jTF_SoCMND_pn_ThongTinCaNhan;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel jpn_QuanLyHoaDon;
    private javax.swing.JPanel jpn_QuanLyKhachHang;
    private javax.swing.JPanel jpn_QuanLySanPhamKho;
    private javax.swing.JPanel jpn_QuanLyThanhToan;
    private javax.swing.JPanel jpn_ThongTinCaNhan;
    // End of variables declaration//GEN-END:variables
}
