/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameMain;
import Data.Data;
import static JFrameMain.jF_ChuCuaHang.Color;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.DefaultButtonModel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.updateComponentTreeUI;

/**
 *
 * @author voanh
 */
public class jFNhanVienKho extends javax.swing.JFrame {
    static String id="";
    static String maChucVu;
    static String mk="";

    static String errorText = "Tên đăng nhập hoặc mật khẩu không hợp lệ !";
    
    
    boolean bThongTinCaNhan = false;
    boolean bQuanLySanPham = false;
    boolean bQuanLyKho = false;
    boolean is_ChinhSua_ThongTinCaNhan = false;
    static Class_Color Color = new Class_Color();
    /**
     * Creates new form jFMain
     */
    public jFNhanVienKho() {
        
        Data d = new Data();
        
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        
        
        
        btn_ThongTinCaNhan.setModel(new FixedStateButtonModel());
        btn_QuanLySanPham.setModel(new FixedStateButtonModel());
        btn_QuanLyKho.setModel(new FixedStateButtonModel());
        btn_Thoat.setModel(new FixedStateButtonModel());

        
        
        //
        btn_ThongTinCaNhan.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
        ThongTinCaNhan_SetAllThingDefault();
        //
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Thoat = new javax.swing.JButton();
        btn_QuanLySanPham = new javax.swing.JButton();
        btn_QuanLyKho = new javax.swing.JButton();
        btn_ThongTinCaNhan = new javax.swing.JButton();
        jpn_ThongTinCaNhan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTF_DiaChi_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jCB_GioiTinh_pn_ThongTinCaNhan = new javax.swing.JComboBox<>();
        jDC_NgaySinh_pn_ThongTinCaNhan = new com.toedter.calendar.JDateChooser();
        jTF_Hoten_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jTF_DienThoai_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jBtn_XacNhan_pn_ThongTinCaNhan = new javax.swing.JButton();
        jBtn_ChinhSua_pn_ThongTinCaNhan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLb_Error_SDT = new javax.swing.JLabel();
        jLb_Error_HoTen = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTF_SoCMND_pn_ThongTinCaNhan = new javax.swing.JTextField();
        jLb_Error_SoCMND = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jpn_QuanLySanPham = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        JNhanVienBanHang_XemHoaDon_btn_TimKiem4 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jTextField14 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        JNhanVienBanHang_XemHoaDon_btn_TimKiem3 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        JNhanVienBanHang_XemHoaDon_btn_TimKiem1 = new javax.swing.JButton();
        jComboBox14 = new javax.swing.JComboBox<>();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jpn_QuanLyKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImages(null);
        setLocationByPlatform(true);
        setName("fLogin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cat-profile-75.png"))); // NOI18N
        jLabel2.setText("PETS STORE");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chào  TUANKYOU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(32, 78, 80));

        btn_Thoat.setBackground(new java.awt.Color(32, 78, 80));
        btn_Thoat.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Exit_Sign_48px.png"))); // NOI18N
        btn_Thoat.setBorder(null);
        btn_Thoat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Thoat.setFocusable(false);
        btn_Thoat.setName(""); // NOI18N
        btn_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseExited(evt);
            }
        });

        btn_QuanLySanPham.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLySanPham.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLySanPham.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLySanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Product_Documents_50px.png"))); // NOI18N
        btn_QuanLySanPham.setBorder(null);
        btn_QuanLySanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLySanPham.setFocusable(false);
        btn_QuanLySanPham.setName(""); // NOI18N
        btn_QuanLySanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamMouseExited(evt);
            }
        });

        btn_QuanLyKho.setBackground(new java.awt.Color(32, 78, 80));
        btn_QuanLyKho.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_QuanLyKho.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_House_50px.png"))); // NOI18N
        btn_QuanLyKho.setBorder(null);
        btn_QuanLyKho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKho.setFocusable(false);
        btn_QuanLyKho.setName(""); // NOI18N
        btn_QuanLyKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhoMouseExited(evt);
            }
        });

        btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 64, 80));
        btn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Personal_Trainer_50px.png"))); // NOI18N
        btn_ThongTinCaNhan.setBorder(null);
        btn_ThongTinCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ThongTinCaNhan.setFocusable(false);
        btn_ThongTinCaNhan.setName(""); // NOI18N
        btn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseExited(evt);
            }
        });
        btn_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 64, 80));
        jpn_ThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_ThongTinCaNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("THÔNG TIN CÁ NHÂN");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_ThongTinCaNhan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1040, 100));

        jLabel3.setBackground(new java.awt.Color(0, 96, 100));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Địa Chỉ");
        jpn_ThongTinCaNhan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 30));

        jLabel4.setBackground(new java.awt.Color(0, 96, 100));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ Tên ");
        jpn_ThongTinCaNhan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 30));

        jLabel5.setBackground(new java.awt.Color(0, 96, 100));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới Tính");
        jpn_ThongTinCaNhan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 30));

        jLabel6.setBackground(new java.awt.Color(0, 96, 100));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Sinh");
        jpn_ThongTinCaNhan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 30));

        jLabel7.setBackground(new java.awt.Color(0, 96, 100));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Điện Thoại");
        jpn_ThongTinCaNhan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 38));

        jTF_DiaChi_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_DiaChi_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_DiaChi_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_DiaChi_pn_ThongTinCaNhan.setText("Củ Chi, Việt Nam");
        jTF_DiaChi_pn_ThongTinCaNhan.setBorder(null);
        jTF_DiaChi_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jpn_ThongTinCaNhan.add(jTF_DiaChi_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 374, 30));

        jCB_GioiTinh_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jCB_GioiTinh_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jCB_GioiTinh_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jCB_GioiTinh_pn_ThongTinCaNhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jCB_GioiTinh_pn_ThongTinCaNhan.setBorder(null);
        jpn_ThongTinCaNhan.add(jCB_GioiTinh_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 30));

        jDC_NgaySinh_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 0, 0));
        jDC_NgaySinh_pn_ThongTinCaNhan.setDateFormatString("dd/MM/yyyy");
        jpn_ThongTinCaNhan.add(jDC_NgaySinh_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 30));

        jTF_Hoten_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_Hoten_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_Hoten_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_Hoten_pn_ThongTinCaNhan.setText("Võ Anh Tuấn");
        jTF_Hoten_pn_ThongTinCaNhan.setBorder(null);
        jTF_Hoten_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jpn_ThongTinCaNhan.add(jTF_Hoten_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 30));

        jTF_DienThoai_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_DienThoai_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_DienThoai_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_DienThoai_pn_ThongTinCaNhan.setText("001672038391");
        jTF_DienThoai_pn_ThongTinCaNhan.setBorder(null);
        jTF_DienThoai_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTF_DienThoai_pn_ThongTinCaNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_DienThoai_pn_ThongTinCaNhanKeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTF_DienThoai_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 200, 30));

        jBtn_XacNhan_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        jBtn_XacNhan_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_XacNhan_pn_ThongTinCaNhan.setText("Xác Nhận");
        jBtn_XacNhan_pn_ThongTinCaNhan.setBorder(null);
        jBtn_XacNhan_pn_ThongTinCaNhan.setFocusable(false);
        jBtn_XacNhan_pn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jBtn_XacNhan_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 125, 47));

        jBtn_ChinhSua_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        jBtn_ChinhSua_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_ChinhSua_pn_ThongTinCaNhan.setText("Chỉnh Sửa");
        jBtn_ChinhSua_pn_ThongTinCaNhan.setBorder(null);
        jBtn_ChinhSua_pn_ThongTinCaNhan.setFocusable(false);
        jBtn_ChinhSua_pn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jBtn_ChinhSua_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 125, 47));
        jpn_ThongTinCaNhan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 374, -1));

        jLb_Error_SDT.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_SDT.setText("*Số điện thoại không hợp lệ");
        jpn_ThongTinCaNhan.add(jLb_Error_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, 30));

        jLb_Error_HoTen.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_HoTen.setText("*Tên đăng nhập không chứa ký tự đặt biệt");
        jpn_ThongTinCaNhan.add(jLb_Error_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, 30));

        jLabel15.setBackground(new java.awt.Color(0, 96, 100));
        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Số CMND");
        jpn_ThongTinCaNhan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 100, 38));

        jTF_SoCMND_pn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jTF_SoCMND_pn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTF_SoCMND_pn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        jTF_SoCMND_pn_ThongTinCaNhan.setText("001672038391");
        jTF_SoCMND_pn_ThongTinCaNhan.setBorder(null);
        jTF_SoCMND_pn_ThongTinCaNhan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTF_SoCMND_pn_ThongTinCaNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_SoCMND_pn_ThongTinCaNhanKeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTF_SoCMND_pn_ThongTinCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 200, 30));

        jLb_Error_SoCMND.setForeground(new java.awt.Color(255, 153, 102));
        jLb_Error_SoCMND.setText("*Số CMND không hợp lệ");
        jpn_ThongTinCaNhan.add(jLb_Error_SoCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, 30));
        jpn_ThongTinCaNhan.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, -1));

        jpn_QuanLySanPham.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLySanPham.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        jpn_QuanLySanPham.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_QuanLySanPham.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("QUẢN LÝ SẢN PHẨM");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_QuanLySanPham.add(jLabel17);
        jLabel17.setBounds(30, 0, 1040, 100);

        jTabbedPane1.setBackground(new java.awt.Color(0, 64, 80));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Roboto Lt", 0, 20)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 64, 80));
        jPanel1.setForeground(new java.awt.Color(0, 90, 90));
        jPanel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.setLayout(null);

        jComboBox3.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giống vật nuôi" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(270, 30, 190, 30);

        jComboBox4.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(30, 80, 190, 30);

        jComboBox5.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loài vật nuôi" }));
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(30, 30, 190, 30);

        jTextField5.setBackground(new java.awt.Color(0, 60, 60));
        jTextField5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Đơn giá");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(780, 30, 190, 30);

        jTextField6.setBackground(new java.awt.Color(0, 60, 60));
        jTextField6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("Đơn giá");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(780, 80, 190, 30);

        jTextField7.setBackground(new java.awt.Color(0, 60, 60));
        jTextField7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("Mã vật nuôi");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(520, 30, 190, 30);

        jTextField8.setBackground(new java.awt.Color(0, 60, 60));
        jTextField8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("Mã sản phẩm");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(270, 80, 190, 30);

        jTextField9.setBackground(new java.awt.Color(0, 60, 60));
        jTextField9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("Tên sản phẩm");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(520, 80, 190, 30);

        JNhanVienBanHang_XemHoaDon_btn_TimKiem4.setBackground(new java.awt.Color(0, 120, 215));
        JNhanVienBanHang_XemHoaDon_btn_TimKiem4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_btn_TimKiem4.setForeground(new java.awt.Color(255, 255, 255));
        JNhanVienBanHang_XemHoaDon_btn_TimKiem4.setText("Xác nhận");
        JNhanVienBanHang_XemHoaDon_btn_TimKiem4.setFocusable(false);
        JNhanVienBanHang_XemHoaDon_btn_TimKiem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemHoaDon_btn_TimKiem4ActionPerformed(evt);
            }
        });
        jPanel1.add(JNhanVienBanHang_XemHoaDon_btn_TimKiem4);
        JNhanVienBanHang_XemHoaDon_btn_TimKiem4.setBounds(430, 150, 130, 41);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(30, 130, 940, 10);

        jTabbedPane1.addTab("Thêm sản phẩm", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 64, 80));
        jPanel4.setLayout(null);

        jComboBox9.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox9.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loài vật nuôi" }));
        jPanel4.add(jComboBox9);
        jComboBox9.setBounds(30, 30, 190, 30);

        jTextField14.setBackground(new java.awt.Color(0, 60, 60));
        jTextField14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("Tên sản phẩm");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField14);
        jTextField14.setBounds(520, 80, 190, 30);

        jTextField16.setBackground(new java.awt.Color(0, 60, 60));
        jTextField16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setText("Đơn giá");
        jPanel4.add(jTextField16);
        jTextField16.setBounds(780, 30, 190, 30);

        jTextField15.setBackground(new java.awt.Color(0, 60, 60));
        jTextField15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("Đơn giá");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField15);
        jTextField15.setBounds(780, 80, 190, 30);

        jComboBox12.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox12.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm" }));
        jPanel4.add(jComboBox12);
        jComboBox12.setBounds(30, 80, 190, 30);

        jComboBox13.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox13.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giống vật nuôi" }));
        jPanel4.add(jComboBox13);
        jComboBox13.setBounds(270, 30, 190, 30);

        JNhanVienBanHang_XemHoaDon_btn_TimKiem3.setBackground(new java.awt.Color(0, 120, 215));
        JNhanVienBanHang_XemHoaDon_btn_TimKiem3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_btn_TimKiem3.setForeground(new java.awt.Color(255, 255, 255));
        JNhanVienBanHang_XemHoaDon_btn_TimKiem3.setText("Xác nhận");
        JNhanVienBanHang_XemHoaDon_btn_TimKiem3.setFocusable(false);
        JNhanVienBanHang_XemHoaDon_btn_TimKiem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemHoaDon_btn_TimKiem3ActionPerformed(evt);
            }
        });
        jPanel4.add(JNhanVienBanHang_XemHoaDon_btn_TimKiem3);
        JNhanVienBanHang_XemHoaDon_btn_TimKiem3.setBounds(430, 150, 130, 41);

        jTextField10.setBackground(new java.awt.Color(0, 60, 60));
        jTextField10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("Mã sản phẩm");
        jPanel4.add(jTextField10);
        jTextField10.setBounds(270, 80, 190, 30);

        jTextField11.setBackground(new java.awt.Color(0, 60, 60));
        jTextField11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("Mã vật nuôi");
        jPanel4.add(jTextField11);
        jTextField11.setBounds(520, 30, 190, 30);

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator8);
        jSeparator8.setBounds(30, 130, 940, 10);

        jTabbedPane1.addTab("Sửa sản phẩm", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 64, 80));
        jPanel5.setLayout(null);

        jComboBox6.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loài vật nuôi" }));
        jComboBox6.setToolTipText("");
        jPanel5.add(jComboBox6);
        jComboBox6.setBounds(30, 30, 190, 30);

        jComboBox8.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox8.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giống vật nuôi" }));
        jComboBox8.setToolTipText("");
        jPanel5.add(jComboBox8);
        jComboBox8.setBounds(270, 30, 190, 30);

        JNhanVienBanHang_XemHoaDon_btn_TimKiem1.setBackground(new java.awt.Color(0, 120, 215));
        JNhanVienBanHang_XemHoaDon_btn_TimKiem1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_btn_TimKiem1.setForeground(new java.awt.Color(255, 255, 255));
        JNhanVienBanHang_XemHoaDon_btn_TimKiem1.setText("Xác nhận");
        JNhanVienBanHang_XemHoaDon_btn_TimKiem1.setFocusable(false);
        JNhanVienBanHang_XemHoaDon_btn_TimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemHoaDon_btn_TimKiem1ActionPerformed(evt);
            }
        });
        jPanel5.add(JNhanVienBanHang_XemHoaDon_btn_TimKiem1);
        JNhanVienBanHang_XemHoaDon_btn_TimKiem1.setBounds(430, 150, 130, 41);

        jComboBox14.setBackground(new java.awt.Color(0, 60, 60));
        jComboBox14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox14.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm" }));
        jComboBox14.setToolTipText("");
        jPanel5.add(jComboBox14);
        jComboBox14.setBounds(30, 80, 190, 30);

        jTextField12.setBackground(new java.awt.Color(0, 60, 60));
        jTextField12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("Mã sản phẩm");
        jTextField12.setToolTipText("");
        jPanel5.add(jTextField12);
        jTextField12.setBounds(270, 80, 190, 30);

        jTextField13.setBackground(new java.awt.Color(0, 60, 60));
        jTextField13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setText("Mã vật nuôi");
        jTextField13.setToolTipText("");
        jPanel5.add(jTextField13);
        jTextField13.setBounds(520, 30, 190, 30);

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator9);
        jSeparator9.setBounds(30, 130, 940, 10);

        jTabbedPane1.addTab("Xóa sản phẩm", jPanel5);

        jpn_QuanLySanPham.add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 120, 1010, 240);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Roboto Lt", 0, 20)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 120, 120));
        jPanel6.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 90, 90));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã loài vật nuôi", "Mã giống vật nuôi", "Mã vật nuôi", "Đơn giá"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getTableHeader().setBackground(new java.awt.Color(0, 60, 60));
        jTable1.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setFont(new java.awt.Font("Roboto", 1, 16));

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1005, 210);

        jTabbedPane2.addTab("Bảng vật nuôi", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 120, 120));
        jPanel7.setLayout(null);

        jTable2.setBackground(new java.awt.Color(0, 90, 90));
        jTable2.setFont(new java.awt.Font("Roboto Lt", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã loại sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(20);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getTableHeader().setBackground(new java.awt.Color(0, 60, 60));
        jTable2.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        jTable2.getTableHeader().setFont(new java.awt.Font("Roboto", 1, 16));

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 1005, 210);

        jTabbedPane2.addTab("Bảng sản phẩm", jPanel7);

        jpn_QuanLySanPham.add(jTabbedPane2);
        jTabbedPane2.setBounds(30, 400, 1010, 240);
        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        jpn_QuanLyKho.setBackground(new java.awt.Color(0, 64, 80));
        jpn_QuanLyKho.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_QuanLyKho.setLayout(null);

        jLabel10.setText("Quản Lý Kho");
        jpn_QuanLyKho.add(jLabel10);
        jLabel10.setBounds(130, 130, 456, 107);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpn_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ExitProgram();
    }//GEN-LAST:event_formWindowClosing

    private void btn_QuanLySanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamMouseEntered
        if(bQuanLySanPham == false)
            btn_QuanLySanPham.setBackground(Color.btn_When_Enter);
        btn_QuanLySanPham.setText("QUẢN LÝ SẢN PHẨM");
    }//GEN-LAST:event_btn_QuanLySanPhamMouseEntered

    private void btn_QuanLyKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseEntered
        if(bQuanLyKho == false)
            btn_QuanLyKho.setBackground(Color.btn_When_Enter);
        btn_QuanLyKho.setText("QUẢN LÝ KHO");
    }//GEN-LAST:event_btn_QuanLyKhoMouseEntered

    private void btn_ThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseEntered
        btn_Thoat.setBackground(Color.btn_When_Enter);
        btn_Thoat.setText("THOÁT");
    }//GEN-LAST:event_btn_ThoatMouseEntered

    private void btn_QuanLySanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamMouseExited
        if(bQuanLySanPham==false)
            btn_QuanLySanPham.setBackground(Color.btn_Default);
        btn_QuanLySanPham.setText("");
    }//GEN-LAST:event_btn_QuanLySanPhamMouseExited

    private void btn_QuanLyKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseExited
        if(bQuanLyKho==false)
            btn_QuanLyKho.setBackground(Color.btn_Default);
        btn_QuanLyKho.setText("");
    }//GEN-LAST:event_btn_QuanLyKhoMouseExited

    private void btn_ThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseExited
        btn_Thoat.setBackground(Color.btn_Default);
        btn_Thoat.setText("");
    }//GEN-LAST:event_btn_ThoatMouseExited

    private void btn_ThongTinCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseEntered
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(Color.btn_When_Enter);
        btn_ThongTinCaNhan.setText("THÔNG TIN CÁ NHÂN");
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseEntered

    private void btn_ThongTinCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseExited
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(Color.btn_Default);
        btn_ThongTinCaNhan.setText("");
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseExited

    private void btn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_ThongTinCaNhan.setBackground(Color.btn_When_Click);
        ThongTinCaNhan_SetAllThingDefault();
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseClicked

    private void btn_QuanLySanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLySanPham.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLySanPham = true;
        SetAllPanelDissapear();
        jpn_QuanLySanPham.setVisible(true);
    }//GEN-LAST:event_btn_QuanLySanPhamMouseClicked

    private void btn_QuanLyKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhoMouseClicked
        SetColorAllButton(Color.btn_Default);
        btn_QuanLyKho.setBackground(Color.btn_When_Click);
        SetFalseAllButton();
        bQuanLyKho = true;
        SetAllPanelDissapear();
        jpn_QuanLyKho.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyKhoMouseClicked

    private void btn_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongTinCaNhanActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void JNhanVienBanHang_XemHoaDon_btn_TimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiem1ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void JNhanVienBanHang_XemHoaDon_btn_TimKiem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiem3ActionPerformed

    private void JNhanVienBanHang_XemHoaDon_btn_TimKiem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiem4ActionPerformed

    private void jTF_DienThoai_pn_ThongTinCaNhanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_DienThoai_pn_ThongTinCaNhanKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))|| vchar == KeyEvent.VK_BACKSPACE || vchar == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_jTF_DienThoai_pn_ThongTinCaNhanKeyTyped

    private void jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked
        // Nếu Xác Nhận Thông Tin Thành Công
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(false);
        ThongTinCaNhan_SetAllTextFieldDisable();
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(true);
        // Cập nhật lại class và gửi thông tin thay đổi về database
    }//GEN-LAST:event_jBtn_XacNhan_pn_ThongTinCaNhanMouseClicked

    private void jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked
        is_ChinhSua_ThongTinCaNhan = true;
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(false);
        ThongTinCaNhan_SetAllTextFieldEnable();
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(true);
    }//GEN-LAST:event_jBtn_ChinhSua_pn_ThongTinCaNhanMouseClicked

    private void jTF_SoCMND_pn_ThongTinCaNhanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_SoCMND_pn_ThongTinCaNhanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SoCMND_pn_ThongTinCaNhanKeyTyped
    
    void ThongTinCaNhan_SetAllTextFieldDisable(){
        ThongTinCaNhan_SetAllTextField(false);
        ThongTinCaNhan_SetAllTextFieldColor(Color.tf_Disable_Edited);
    }
    
    void ThongTinCaNhan_SetAllThingDefault(){
        /*
        Đổ lại dữ liệu trong class
        */
        ThongTinCaNhan_SetAllTextFieldDisable();
        jBtn_ChinhSua_pn_ThongTinCaNhan.setEnabled(true);
        jBtn_XacNhan_pn_ThongTinCaNhan.setEnabled(false);
    }
    void ThongTinCaNhan_SetAllTextFieldEnable(){
        ThongTinCaNhan_SetAllTextField(true);
        ThongTinCaNhan_SetAllTextFieldColor(Color.tf_Enable_Edited);
    }
        void ThongTinCaNhan_SetAllTextFieldColor(java.awt.Color jColor){
        jTF_DiaChi_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_DienThoai_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_Hoten_pn_ThongTinCaNhan.setBackground(jColor);
        jTF_SoCMND_pn_ThongTinCaNhan.setBackground(jColor);
    }    
        
    void ThongTinCaNhan_SetAllTextField(boolean x){
        jTF_DiaChi_pn_ThongTinCaNhan.setEnabled(x);
        jTF_DienThoai_pn_ThongTinCaNhan.setEnabled(x);
        jTF_Hoten_pn_ThongTinCaNhan.setEnabled(x);
        jTF_SoCMND_pn_ThongTinCaNhan.setEnabled(x);
        jCB_GioiTinh_pn_ThongTinCaNhan.setEnabled(x);
        jDC_NgaySinh_pn_ThongTinCaNhan.setEnabled(x);
    }    
    void SetColorAllButton(java.awt.Color jColor ){
        btn_ThongTinCaNhan.setBackground(jColor);
        btn_QuanLyKho.setBackground(jColor);
        btn_QuanLySanPham.setBackground(jColor);
        btn_Thoat.setBackground(jColor);
    }
    
    void SetFalseAllButton(){
        bThongTinCaNhan = false;
        bQuanLySanPham = false;
        bQuanLyKho = false;
    }
    void SetAllPanelDissapear(){
        jpn_QuanLyKho.setVisible(false);
        jpn_QuanLySanPham.setVisible(false);
        jpn_ThongTinCaNhan.setVisible(false);
    }
    void ExitProgram(){
        int output = JOptionPane.showConfirmDialog(this,"Bạn có thật sự muốn thoát không ?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(output==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else
            return;
    }
    /**
     * @param args the command line arguments
     */
    
    public class FixedStateButtonModel extends DefaultButtonModel    {

        @Override
        public boolean isPressed() {
            return false;
        }

        @Override
        public boolean isRollover() {
            return false;
        }

        @Override
        public void setRollover(boolean b) {
            //NOOP
        }

    }
    
    public static void mmmain(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFNhanVienKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JNhanVienBanHang_XemHoaDon_btn_TimKiem1;
    private javax.swing.JButton JNhanVienBanHang_XemHoaDon_btn_TimKiem3;
    private javax.swing.JButton JNhanVienBanHang_XemHoaDon_btn_TimKiem4;
    private javax.swing.JButton btn_QuanLyKho;
    private javax.swing.JButton btn_QuanLySanPham;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_ThongTinCaNhan;
    private javax.swing.JButton jBtn_ChinhSua_pn_ThongTinCaNhan;
    private javax.swing.JButton jBtn_XacNhan_pn_ThongTinCaNhan;
    private javax.swing.JComboBox<String> jCB_GioiTinh_pn_ThongTinCaNhan;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDC_NgaySinh_pn_ThongTinCaNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLb_Error_HoTen;
    private javax.swing.JLabel jLb_Error_SDT;
    private javax.swing.JLabel jLb_Error_SoCMND;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTF_DiaChi_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_DienThoai_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_Hoten_pn_ThongTinCaNhan;
    private javax.swing.JTextField jTF_SoCMND_pn_ThongTinCaNhan;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel jpn_QuanLyKho;
    private javax.swing.JPanel jpn_QuanLySanPham;
    private javax.swing.JPanel jpn_ThongTinCaNhan;
    // End of variables declaration//GEN-END:variables
}
