/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrameMain;
import Data.Data;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.DefaultButtonModel;

/**
 *
 * @author voanh
 */
public class jFNhanVienBanHang extends javax.swing.JFrame {
    static String id="";
    static String maChucVu;
    static String mk="";

    static String errorText = "Tên đăng nhập hoặc mật khẩu không hợp lệ !";
    
    
    boolean bThongTinCaNhan = false;
    boolean bQuanLyKhachHang = false;
    boolean bQuanLyHoaDon = false;
    boolean bQuanLyThanhToan = false;
    boolean bQuanLySanPhamKho = false;

    
    /**
     * Creates new form jFMain
     */
    public jFNhanVienBanHang() {
        
         Data d = new Data();
        
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        
        
        
        btn_ThongTinCaNhan.setModel(new FixedStateButtonModel());
        btn_QuanLyKhachHang.setModel(new FixedStateButtonModel());
        btn_QuanLyHoaDon.setModel(new FixedStateButtonModel());
        btn_QuanLySanPhamKho.setModel(new FixedStateButtonModel());
        btn_Thoat.setModel(new FixedStateButtonModel());
        btn_QuanLyThanhToan.setModel(new FixedStateButtonModel());
        
        
        //
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_ThongTinCaNhan.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
        //
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Thoat = new javax.swing.JButton();
        btn_QuanLyKhachHang = new javax.swing.JButton();
        btn_QuanLyHoaDon = new javax.swing.JButton();
        btn_QuanLySanPhamKho = new javax.swing.JButton();
        btn_QuanLyThanhToan = new javax.swing.JButton();
        btn_ThongTinCaNhan = new javax.swing.JButton();
        jpn_ThongTinCaNhan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jpn_QuanLyKhachHang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpn_QuanLySanPhamKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpn_QuanLyHoaDon = new javax.swing.JPanel();
        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_time_Time = new com.toedter.calendar.JDateChooser();
        JNhanVienBanHang_XemHoaDon_btn_TimKiem = new javax.swing.JButton();
        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon = new javax.swing.JTable();
        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_Tong = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jpn_QuanLyThanhToan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImages(null);
        setLocationByPlatform(true);
        setName("fLogin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cat-profile-75.png"))); // NOI18N
        jLabel2.setText("PETS STORE");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chào  TUANKYOU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 120, 215));

        btn_Thoat.setBackground(new java.awt.Color(0, 120, 215));
        btn_Thoat.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setText("Thoát");
        btn_Thoat.setBorder(null);
        btn_Thoat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Thoat.setFocusable(false);
        btn_Thoat.setName(""); // NOI18N
        btn_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseExited(evt);
            }
        });

        btn_QuanLyKhachHang.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyKhachHang.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyKhachHang.setText("Quản Lý Khách Hàng");
        btn_QuanLyKhachHang.setBorder(null);
        btn_QuanLyKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyKhachHang.setFocusable(false);
        btn_QuanLyKhachHang.setName(""); // NOI18N
        btn_QuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhachHangMouseExited(evt);
            }
        });

        btn_QuanLyHoaDon.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyHoaDon.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyHoaDon.setText("Quản Lý Hóa Đơn");
        btn_QuanLyHoaDon.setBorder(null);
        btn_QuanLyHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyHoaDon.setFocusable(false);
        btn_QuanLyHoaDon.setName(""); // NOI18N
        btn_QuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyHoaDonMouseExited(evt);
            }
        });

        btn_QuanLySanPhamKho.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLySanPhamKho.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLySanPhamKho.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLySanPhamKho.setText("Quản Lý Sản Phẩm/Kho");
        btn_QuanLySanPhamKho.setBorder(null);
        btn_QuanLySanPhamKho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLySanPhamKho.setFocusable(false);
        btn_QuanLySanPhamKho.setName(""); // NOI18N
        btn_QuanLySanPhamKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLySanPhamKhoMouseExited(evt);
            }
        });

        btn_QuanLyThanhToan.setBackground(new java.awt.Color(0, 120, 215));
        btn_QuanLyThanhToan.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_QuanLyThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuanLyThanhToan.setText("Quản Lý Thanh Toán");
        btn_QuanLyThanhToan.setBorder(null);
        btn_QuanLyThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QuanLyThanhToan.setFocusable(false);
        btn_QuanLyThanhToan.setName(""); // NOI18N
        btn_QuanLyThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyThanhToanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_QuanLyThanhToanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_QuanLyThanhToanMouseExited(evt);
            }
        });

        btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
        btn_ThongTinCaNhan.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_ThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThongTinCaNhan.setText("Thông Tin Cá Nhân");
        btn_ThongTinCaNhan.setBorder(null);
        btn_ThongTinCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ThongTinCaNhan.setFocusable(false);
        btn_ThongTinCaNhan.setName(""); // NOI18N
        btn_ThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThongTinCaNhanMouseExited(evt);
            }
        });
        btn_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinCaNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 120));
        jpn_ThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1070, 720));
        jpn_ThongTinCaNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 96, 100));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Địa Chỉ");
        jpn_ThongTinCaNhan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 30));

        jLabel4.setBackground(new java.awt.Color(0, 96, 100));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ Tên ");
        jpn_ThongTinCaNhan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 30));

        jLabel5.setBackground(new java.awt.Color(0, 96, 100));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới Tính");
        jpn_ThongTinCaNhan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 30));

        jLabel6.setBackground(new java.awt.Color(0, 96, 100));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Sinh");
        jpn_ThongTinCaNhan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 30));

        jLabel7.setBackground(new java.awt.Color(0, 96, 100));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Điện Thoại");
        jpn_ThongTinCaNhan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 38));

        jTextField1.setBackground(new java.awt.Color(0, 120, 120));
        jTextField1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Củ Chi, Việt Nam");
        jTextField1.setBorder(null);
        jpn_ThongTinCaNhan.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 374, 30));

        jComboBox1.setBackground(new java.awt.Color(0, 120, 120));
        jComboBox1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jComboBox1.setBorder(null);
        jpn_ThongTinCaNhan.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 30));

        jDateChooser1.setBackground(new java.awt.Color(0, 0, 0));
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jpn_ThongTinCaNhan.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 30));

        jTextField2.setBackground(new java.awt.Color(0, 120, 120));
        jTextField2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Võ Anh Tuấn");
        jTextField2.setBorder(null);
        jpn_ThongTinCaNhan.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 30));

        jTextField3.setBackground(new java.awt.Color(0, 120, 120));
        jTextField3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("001672038391");
        jTextField3.setBorder(null);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 200, 30));

        jButton1.setBackground(new java.awt.Color(0, 120, 215));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xác Nhận");
        jButton1.setBorder(null);
        jpn_ThongTinCaNhan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 125, 47));

        jButton2.setBackground(new java.awt.Color(0, 120, 215));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Chỉnh Sửa");
        jButton2.setBorder(null);
        jpn_ThongTinCaNhan.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 125, 47));
        jpn_ThongTinCaNhan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));
        jpn_ThongTinCaNhan.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 374, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Thin", 0, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("THÔNG TIN CÁ NHÂN");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpn_ThongTinCaNhan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1040, 100));

        jLabel13.setForeground(new java.awt.Color(255, 153, 102));
        jLabel13.setText("*Số điện thoại không hợp lệ");
        jpn_ThongTinCaNhan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, 30));

        jLabel14.setForeground(new java.awt.Color(255, 153, 102));
        jLabel14.setText("*Tên đăng nhập không chứa ký tự đặt biệt");
        jpn_ThongTinCaNhan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, 30));

        jLabel15.setBackground(new java.awt.Color(0, 96, 100));
        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Số CMND");
        jpn_ThongTinCaNhan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 100, 38));

        jTextField4.setBackground(new java.awt.Color(0, 120, 120));
        jTextField4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("001672038391");
        jTextField4.setBorder(null);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jpn_ThongTinCaNhan.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 200, 30));

        jLabel16.setForeground(new java.awt.Color(255, 153, 102));
        jLabel16.setText("*Số CMND không hợp lệ");
        jpn_ThongTinCaNhan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, 30));
        jpn_ThongTinCaNhan.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 200, -1));

        jpn_QuanLyKhachHang.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLyKhachHang.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quản Lý  Khách Hàng");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jpn_QuanLyKhachHangLayout = new javax.swing.GroupLayout(jpn_QuanLyKhachHang);
        jpn_QuanLyKhachHang.setLayout(jpn_QuanLyKhachHangLayout);
        jpn_QuanLyKhachHangLayout.setHorizontalGroup(
            jpn_QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyKhachHangLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLyKhachHangLayout.setVerticalGroup(
            jpn_QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyKhachHangLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        jpn_QuanLySanPhamKho.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLySanPhamKho.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel10.setText("Quản Lý Sản Phẩm / Kho");

        javax.swing.GroupLayout jpn_QuanLySanPhamKhoLayout = new javax.swing.GroupLayout(jpn_QuanLySanPhamKho);
        jpn_QuanLySanPhamKho.setLayout(jpn_QuanLySanPhamKhoLayout);
        jpn_QuanLySanPhamKhoLayout.setHorizontalGroup(
            jpn_QuanLySanPhamKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLySanPhamKhoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLySanPhamKhoLayout.setVerticalGroup(
            jpn_QuanLySanPhamKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLySanPhamKhoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        jpn_QuanLyHoaDon.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLyHoaDon.setPreferredSize(new java.awt.Dimension(1070, 720));

        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon.setText("TRA CỨU HÓA ĐƠN");

        JNhanVienBanHang_XemHoaDon_time_Time.setDateFormatString("d MMMM, yyyy");
        JNhanVienBanHang_XemHoaDon_time_Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JNhanVienBanHang_XemHoaDon_btn_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_btn_TimKiem.setText("Tìm kiếm");
        JNhanVienBanHang_XemHoaDon_btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed(evt);
            }
        });

        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon.setText("Bảng Hóa Đơn");

        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "NV001", "01/01/2017", "KH002"},
                {"002", "NV003", "01/02/2017", "KH110"},
                {"003", "NV001", "04/02/2017", "KH103"},
                {"004", "NV003", "07/03/2017", "KH106"},
                {"007", "NV004", "08/03/2017", "KH204"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Người lập hóa đơn", "Ngày lập hóa đơn", "Khách hàng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setGridColor(new java.awt.Color(255, 255, 255));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setRowHeight(20);
        jScrollPane3.setViewportView(JNhanVienBanHang_XemHoaDon_tb_BangHoaDon);

        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Loại sản phẩm", "Tên sản phẩm", "Giá", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setGridColor(new java.awt.Color(255, 255, 255));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setMinimumSize(new java.awt.Dimension(60, 480));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setPreferredSize(new java.awt.Dimension(300, 480));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setRowHeight(20);
        jScrollPane1.setViewportView(JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon);

        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien.setText("...................................");

        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien.setText("Tên nhân viên:");

        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang.setText("Tên khách hàng:");

        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang.setText("...................................");

        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon.setText("Bảng Chi Tiết Hóa Đơn");

        JNhanVienBanHang_XemHoaDon_lb_Tong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_Tong.setText("Tổng:");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_QuanLyHoaDonLayout = new javax.swing.GroupLayout(jpn_QuanLyHoaDon);
        jpn_QuanLyHoaDon.setLayout(jpn_QuanLyHoaDonLayout);
        jpn_QuanLyHoaDonLayout.setHorizontalGroup(
            jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 13, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))
                                .addContainerGap())))
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemHoaDon_time_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JNhanVienBanHang_XemHoaDon_btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_QuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JNhanVienBanHang_XemHoaDon_lb_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpn_QuanLyHoaDonLayout.setVerticalGroup(
            jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JNhanVienBanHang_XemHoaDon_lb_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNhanVienBanHang_XemHoaDon_btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JNhanVienBanHang_XemHoaDon_time_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangHoaDon)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon))
                        .addGap(21, 21, 21)
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jpn_QuanLyHoaDonLayout.createSequentialGroup()
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenNhanVien)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_TenKhachHang)
                            .addComponent(JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang))))
                .addGap(18, 18, 18)
                .addGroup(jpn_QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNhanVienBanHang_XemHoaDon_lb_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jpn_QuanLyThanhToan.setBackground(new java.awt.Color(0, 120, 120));
        jpn_QuanLyThanhToan.setPreferredSize(new java.awt.Dimension(1070, 720));

        jLabel11.setText("Quản Lý Thanh Toán");

        javax.swing.GroupLayout jpn_QuanLyThanhToanLayout = new javax.swing.GroupLayout(jpn_QuanLyThanhToan);
        jpn_QuanLyThanhToan.setLayout(jpn_QuanLyThanhToanLayout);
        jpn_QuanLyThanhToanLayout.setHorizontalGroup(
            jpn_QuanLyThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyThanhToanLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jpn_QuanLyThanhToanLayout.setVerticalGroup(
            jpn_QuanLyThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_QuanLyThanhToanLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpn_QuanLySanPhamKho, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_ThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpn_QuanLyThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ExitProgram();
    }//GEN-LAST:event_formWindowClosing

    private void btn_QuanLyKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangMouseEntered
        if(bQuanLyKhachHang == false)
            btn_QuanLyKhachHang.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLyKhachHangMouseEntered

    private void btn_QuanLyHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonMouseEntered
        if(bQuanLyHoaDon == false)
            btn_QuanLyHoaDon.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLyHoaDonMouseEntered

    private void btn_QuanLyThanhToanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThanhToanMouseEntered
        if(bQuanLyThanhToan == false)
            btn_QuanLyThanhToan.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLyThanhToanMouseEntered

    private void btn_QuanLySanPhamKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamKhoMouseEntered
        if(bQuanLySanPhamKho==false)
            btn_QuanLySanPhamKho.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_QuanLySanPhamKhoMouseEntered

    private void btn_ThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseEntered
        btn_Thoat.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_ThoatMouseEntered

    private void btn_QuanLyKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangMouseExited
        if(bQuanLyKhachHang==false)
            btn_QuanLyKhachHang.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLyKhachHangMouseExited

    private void btn_QuanLyHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonMouseExited
        if(bQuanLyHoaDon==false)
            btn_QuanLyHoaDon.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLyHoaDonMouseExited

    private void btn_QuanLyThanhToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThanhToanMouseExited
        if(bQuanLyThanhToan==false)
            btn_QuanLyThanhToan.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLyThanhToanMouseExited

    private void btn_QuanLySanPhamKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamKhoMouseExited
        if(bQuanLySanPhamKho==false)
            btn_QuanLySanPhamKho.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_QuanLySanPhamKhoMouseExited

    private void btn_ThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseExited
        btn_Thoat.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_ThoatMouseExited

    private void btn_ThongTinCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseEntered
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 100, 215));
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseEntered

    private void btn_ThongTinCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseExited
        if(bThongTinCaNhan==false)
            btn_ThongTinCaNhan.setBackground(new java.awt.Color(0, 120, 215));
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseExited

    private void btn_ThongTinCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_ThongTinCaNhan.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bThongTinCaNhan = true;
        SetAllPanelDissapear();
        jpn_ThongTinCaNhan.setVisible(true);
    }//GEN-LAST:event_btn_ThongTinCaNhanMouseClicked

    private void btn_QuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLyKhachHang.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLyKhachHang = true;
        SetAllPanelDissapear();
        jpn_QuanLyKhachHang.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyKhachHangMouseClicked

    private void btn_QuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLyHoaDon.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLyHoaDon = true;
        SetAllPanelDissapear();
        jpn_QuanLyHoaDon.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyHoaDonMouseClicked

    private void btn_QuanLyThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyThanhToanMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLyThanhToan.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLyThanhToan = true;
        SetAllPanelDissapear();
        jpn_QuanLyThanhToan.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyThanhToanMouseClicked

    private void btn_QuanLySanPhamKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySanPhamKhoMouseClicked
        SetColorAllButton(new java.awt.Color (0,120,215));
        btn_QuanLySanPhamKho.setBackground(new java.awt.Color (0,120,120));
        SetFalseAllButton();
        bQuanLySanPhamKho = true;
        SetAllPanelDissapear();
        jpn_QuanLySanPhamKho.setVisible(true);
    }//GEN-LAST:event_btn_QuanLySanPhamKhoMouseClicked

    private void btn_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongTinCaNhanActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar))|| vchar == KeyEvent.VK_BACKSPACE || vchar == KeyEvent.VK_DELETE){
           evt.consume();
       }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed
    
    
    void SetColorAllButton(java.awt.Color jColor ){
        btn_ThongTinCaNhan.setBackground(jColor);
        btn_QuanLyHoaDon.setBackground(jColor);
        btn_QuanLyKhachHang.setBackground(jColor);
        btn_QuanLySanPhamKho.setBackground(jColor);
        btn_Thoat.setBackground(jColor);
        btn_QuanLyThanhToan.setBackground(jColor);
    }
    
    void SetFalseAllButton(){
        bThongTinCaNhan = false;
        bQuanLyKhachHang = false;
        bQuanLyHoaDon = false;
        bQuanLyThanhToan = false;
        bQuanLySanPhamKho = false;
    }
    void SetAllPanelDissapear(){
        jpn_QuanLySanPhamKho.setVisible(false);
        jpn_QuanLyKhachHang.setVisible(false);
        jpn_QuanLyHoaDon.setVisible(false);
        jpn_QuanLyThanhToan.setVisible(false);
        jpn_ThongTinCaNhan.setVisible(false);
    }
    void ExitProgram(){
        int output = JOptionPane.showConfirmDialog(this,"Bạn có thật sự muốn thoát không ?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(output==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else
            return;
    }
    /**
     * @param args the command line arguments
     */
    
    public class FixedStateButtonModel extends DefaultButtonModel    {

        @Override
        public boolean isPressed() {
            return false;
        }

        @Override
        public boolean isRollover() {
            return false;
        }

        @Override
        public void setRollover(boolean b) {
            //NOOP
        }

    }
    
    public static void mmmain(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFNhanVienBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JNhanVienBanHang_XemHoaDon_btn_TimKiem;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_BangHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_TenKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_TenNhanVien;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_Tong;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_XemHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien;
    private javax.swing.JTable JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon;
    private javax.swing.JTable JNhanVienBanHang_XemHoaDon_tb_BangHoaDon;
    private com.toedter.calendar.JDateChooser JNhanVienBanHang_XemHoaDon_time_Time;
    private javax.swing.JButton btn_QuanLyHoaDon;
    private javax.swing.JButton btn_QuanLyKhachHang;
    private javax.swing.JButton btn_QuanLySanPhamKho;
    private javax.swing.JButton btn_QuanLyThanhToan;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_ThongTinCaNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel jpn_QuanLyHoaDon;
    private javax.swing.JPanel jpn_QuanLyKhachHang;
    private javax.swing.JPanel jpn_QuanLySanPhamKho;
    private javax.swing.JPanel jpn_QuanLyThanhToan;
    private javax.swing.JPanel jpn_ThongTinCaNhan;
    // End of variables declaration//GEN-END:variables
}
