package ChuCuaHang;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAIHUUTUAN
 */
public class JChuCuaHang extends javax.swing.JFrame {

    /**
     * Creates new form JChuCuaHang
     */
    public JChuCuaHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JChuCuaHang_btn_ThemNhanVien = new javax.swing.JButton();
        JChuCuaHang_btn_SuaNhanVien = new javax.swing.JButton();
        JChuCuaHang_btn_XoaNhanVien = new javax.swing.JButton();
        JChuCuaHang_btn_ThemLoaiSP = new javax.swing.JButton();
        JChuCuaHang_btn_SuaLoaiSP = new javax.swing.JButton();
        JChuCuaHang_btn_XoaLoaiSP = new javax.swing.JButton();
        JChuCuaHang_btn_XemThuChi = new javax.swing.JButton();
        JChuCuaHang_btn_SuaThuChi = new javax.swing.JButton();
        JChuCuaHang_btn_XemNhapXuatKho = new javax.swing.JButton();
        JChuCuaHang_btn_DongTab = new javax.swing.JButton();
        JChuCuaHang_btn_SuaNhapXuatKho = new javax.swing.JButton();
        JChuCuaHang_btn_XemThongTinCaNhan = new javax.swing.JButton();
        JChuCuaHang_btn_SuaThongTinCaNhan = new javax.swing.JButton();
        JChuCuaHang_btn_ThoatChuongTrinh = new javax.swing.JButton();
        JChuCuaHang_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        JChuCuaHang_btn_ThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_add.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_ThemNhanVien);
        JChuCuaHang_btn_ThemNhanVien.setBounds(0, 0, 90, 90);

        JChuCuaHang_btn_SuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_edit copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_SuaNhanVien);
        JChuCuaHang_btn_SuaNhanVien.setBounds(90, 0, 90, 90);

        JChuCuaHang_btn_XoaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_delete copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_XoaNhanVien);
        JChuCuaHang_btn_XoaNhanVien.setBounds(180, 0, 90, 90);

        JChuCuaHang_btn_ThemLoaiSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_pack copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_ThemLoaiSP);
        JChuCuaHang_btn_ThemLoaiSP.setBounds(270, 0, 90, 90);

        JChuCuaHang_btn_SuaLoaiSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fix_pack copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_SuaLoaiSP);
        JChuCuaHang_btn_SuaLoaiSP.setBounds(360, 0, 90, 90);

        JChuCuaHang_btn_XoaLoaiSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete_pack copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_XoaLoaiSP);
        JChuCuaHang_btn_XoaLoaiSP.setBounds(450, 0, 90, 90);

        JChuCuaHang_btn_XemThuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/KeToan copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_XemThuChi);
        JChuCuaHang_btn_XemThuChi.setBounds(540, 0, 90, 90);

        JChuCuaHang_btn_SuaThuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fix_KeToan copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_SuaThuChi);
        JChuCuaHang_btn_SuaThuChi.setBounds(630, 0, 90, 90);

        JChuCuaHang_btn_XemNhapXuatKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kho copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_XemNhapXuatKho);
        JChuCuaHang_btn_XemNhapXuatKho.setBounds(720, 0, 90, 90);

        JChuCuaHang_btn_DongTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigate_cross copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_DongTab);
        JChuCuaHang_btn_DongTab.setBounds(1170, 0, 90, 90);

        JChuCuaHang_btn_SuaNhapXuatKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/warehouse copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_SuaNhapXuatKho);
        JChuCuaHang_btn_SuaNhapXuatKho.setBounds(810, 0, 90, 90);

        JChuCuaHang_btn_XemThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer-service-icon copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_XemThongTinCaNhan);
        JChuCuaHang_btn_XemThongTinCaNhan.setBounds(990, 0, 90, 90);

        JChuCuaHang_btn_SuaThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/security_agent_edit copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_SuaThongTinCaNhan);
        JChuCuaHang_btn_SuaThongTinCaNhan.setBounds(1080, 0, 90, 90);

        JChuCuaHang_btn_ThoatChuongTrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit copy.png"))); // NOI18N
        getContentPane().add(JChuCuaHang_btn_ThoatChuongTrinh);
        JChuCuaHang_btn_ThoatChuongTrinh.setBounds(1260, 0, 90, 90);

        JChuCuaHang_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/husky-clipart-akita-18.png"))); // NOI18N
        JChuCuaHang_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(JChuCuaHang_logo);
        JChuCuaHang_logo.setBounds(480, 200, 400, 400);

        getAccessibleContext().setAccessibleName("JButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JChuCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JChuCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JChuCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JChuCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JChuCuaHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JChuCuaHang_btn_DongTab;
    private javax.swing.JButton JChuCuaHang_btn_SuaLoaiSP;
    private javax.swing.JButton JChuCuaHang_btn_SuaNhanVien;
    private javax.swing.JButton JChuCuaHang_btn_SuaNhapXuatKho;
    private javax.swing.JButton JChuCuaHang_btn_SuaThongTinCaNhan;
    private javax.swing.JButton JChuCuaHang_btn_SuaThuChi;
    private javax.swing.JButton JChuCuaHang_btn_ThemLoaiSP;
    private javax.swing.JButton JChuCuaHang_btn_ThemNhanVien;
    private javax.swing.JButton JChuCuaHang_btn_ThoatChuongTrinh;
    private javax.swing.JButton JChuCuaHang_btn_XemNhapXuatKho;
    private javax.swing.JButton JChuCuaHang_btn_XemThongTinCaNhan;
    private javax.swing.JButton JChuCuaHang_btn_XemThuChi;
    private javax.swing.JButton JChuCuaHang_btn_XoaLoaiSP;
    private javax.swing.JButton JChuCuaHang_btn_XoaNhanVien;
    private javax.swing.JLabel JChuCuaHang_logo;
    // End of variables declaration//GEN-END:variables
}
