/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package XemSanPham;

/**
 *
 * @author Tu
 */
public class XemSanPham extends javax.swing.JFrame {

    /**
     * Creates new form XemSanPham
     */
    public XemSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JNhanVienBanHang_btn_ThemKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_SuaKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_XoaKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemHoaDon = new javax.swing.JButton();
        JNhanVienBanHang_btn_InHoaDon = new javax.swing.JButton();
        JNhanVienBanHang_btn_ThanhToan = new javax.swing.JButton();
        JNhanVienBanHang_btn_TinhTien = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemKho = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemThongTinSP = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemThongTinCaNhan = new javax.swing.JButton();
        JNhanVienBanHang_btn_SuaThongTinCaNhan = new javax.swing.JButton();
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab = new javax.swing.JButton();
        JNhanVienBanHang_XemSanPham_panel = new javax.swing.JPanel();
        JNhanVienBanHang_XemSanPham_lb_TimKiem = new javax.swing.JLabel();
        jNhanVienBanHang_XemSanPham_tbx_TimKiem = new javax.swing.JTextField();
        JNhanVienBanHang_XemSanPham_btn_TimKiem = new javax.swing.JButton();
        jNhanVienBanHang_XemSanPham_sp_TimKiem = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemSanPham_tb_BangSanPham = new javax.swing.JTable();
        JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham = new javax.swing.JLabel();
        jNhanVienBanHang_XemSanPham_lb_AnhSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_MaSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_LoaiSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_TenSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_DonGia = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_SoLuong = new javax.swing.JLabel();
        jNhanVienBanHang_XemSanPham_tbx_MaSanPham = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_TenSanPham = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_DonGia = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_SoLuong = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        JNhanVienBanHang_btn_ThemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_add copy.png"))); // NOI18N

        JNhanVienBanHang_btn_SuaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_edit copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_view copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XoaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_delete copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/View_ebills_Icon copy.png"))); // NOI18N
        JNhanVienBanHang_btn_XemHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JNhanVienBanHang_btn_XemHoaDonMouseClicked(evt);
            }
        });
        JNhanVienBanHang_btn_XemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_btn_XemHoaDonActionPerformed(evt);
            }
        });

        JNhanVienBanHang_btn_InHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/receipt_printer copy.png"))); // NOI18N

        JNhanVienBanHang_btn_ThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Payments_payment_card_credit copy.png"))); // NOI18N

        JNhanVienBanHang_btn_TinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/scan copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kho copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemThongTinSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-good copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer-service-icon copy.png"))); // NOI18N

        JNhanVienBanHang_btn_SuaThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/security_agent_edit copy.png"))); // NOI18N

        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigate_cross copy.png"))); // NOI18N
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked(evt);
            }
        });

        JNhanVienBanHang_XemSanPham_panel.setPreferredSize(new java.awt.Dimension(1366, 600));

        JNhanVienBanHang_XemSanPham_lb_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_TimKiem.setText("TÌM KIẾM SẢN PHẨM");

        jNhanVienBanHang_XemSanPham_tbx_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed(evt);
            }
        });

        JNhanVienBanHang_XemSanPham_btn_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_btn_TimKiem.setText("Tìm kiếm");
        JNhanVienBanHang_XemSanPham_btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed(evt);
            }
        });

        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Loại sản phẩm", "Tên sản phẩm", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setRowHeight(20);
        jNhanVienBanHang_XemSanPham_sp_TimKiem.setViewportView(JNhanVienBanHang_XemSanPham_tb_BangSanPham);
        if (JNhanVienBanHang_XemSanPham_tb_BangSanPham.getColumnModel().getColumnCount() > 0) {
            JNhanVienBanHang_XemSanPham_tb_BangSanPham.getColumnModel().getColumn(0).setMinWidth(70);
            JNhanVienBanHang_XemSanPham_tb_BangSanPham.getColumnModel().getColumn(0).setMaxWidth(80);
            JNhanVienBanHang_XemSanPham_tb_BangSanPham.getColumnModel().getColumn(1).setMinWidth(100);
            JNhanVienBanHang_XemSanPham_tb_BangSanPham.getColumnModel().getColumn(1).setMaxWidth(100);
            JNhanVienBanHang_XemSanPham_tb_BangSanPham.getColumnModel().getColumn(3).setMinWidth(100);
            JNhanVienBanHang_XemSanPham_tb_BangSanPham.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham.setText("Thông tin sản phẩm");

        jNhanVienBanHang_XemSanPham_lb_AnhSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNhanVienBanHang_XemSanPham_lb_AnhSanPham.setText("    Ảnh sản phẩm");

        JNhanVienBanHang_XemSanPham_lb_MaSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_MaSanPham.setText("Mã sản phẩm:");

        JNhanVienBanHang_XemSanPham_lb_LoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_LoaiSanPham.setText("Loại sản phẩm:");

        JNhanVienBanHang_XemSanPham_lb_TenSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_TenSanPham.setText("Tên sản phẩm:");

        JNhanVienBanHang_XemSanPham_lb_DonGia.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_DonGia.setText("Đơn giá:");

        JNhanVienBanHang_XemSanPham_lb_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_SoLuong.setText("Số lượng:");

        jNhanVienBanHang_XemSanPham_tbx_MaSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_MaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed(evt);
            }
        });

        jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed(evt);
            }
        });

        jNhanVienBanHang_XemSanPham_tbx_TenSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_TenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed(evt);
            }
        });

        jNhanVienBanHang_XemSanPham_tbx_DonGia.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_DonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed(evt);
            }
        });

        jNhanVienBanHang_XemSanPham_tbx_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed(evt);
            }
        });

        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang.setText("Thêm vào giỏ hàng");
        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JNhanVienBanHang_XemSanPham_panelLayout = new javax.swing.GroupLayout(JNhanVienBanHang_XemSanPham_panel);
        JNhanVienBanHang_XemSanPham_panel.setLayout(JNhanVienBanHang_XemSanPham_panelLayout);
        JNhanVienBanHang_XemSanPham_panelLayout.setHorizontalGroup(
            JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                        .addComponent(jNhanVienBanHang_XemSanPham_tbx_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JNhanVienBanHang_XemSanPham_btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jNhanVienBanHang_XemSanPham_sp_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jNhanVienBanHang_XemSanPham_lb_AnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemSanPham_lb_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNhanVienBanHang_XemSanPham_tbx_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemSanPham_lb_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNhanVienBanHang_XemSanPham_tbx_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemSanPham_lb_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNhanVienBanHang_XemSanPham_tbx_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemSanPham_lb_LoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemSanPham_lb_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNhanVienBanHang_XemSanPham_tbx_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addComponent(jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addComponent(JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(260, 260, 260))))))
            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(JNhanVienBanHang_XemSanPham_lb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JNhanVienBanHang_XemSanPham_panelLayout.setVerticalGroup(
            JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham))
                    .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                        .addComponent(JNhanVienBanHang_XemSanPham_lb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNhanVienBanHang_XemSanPham_tbx_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JNhanVienBanHang_XemSanPham_btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                        .addComponent(jNhanVienBanHang_XemSanPham_sp_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                        .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JNhanVienBanHang_XemSanPham_lb_SoLuong)
                                    .addComponent(jNhanVienBanHang_XemSanPham_tbx_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JNhanVienBanHang_XemSanPham_lb_MaSanPham)
                                    .addComponent(jNhanVienBanHang_XemSanPham_tbx_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JNhanVienBanHang_XemSanPham_lb_LoaiSanPham)
                                    .addComponent(jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JNhanVienBanHang_XemSanPham_lb_TenSanPham)
                                    .addComponent(jNhanVienBanHang_XemSanPham_tbx_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(JNhanVienBanHang_XemSanPham_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JNhanVienBanHang_XemSanPham_lb_DonGia)
                                    .addComponent(jNhanVienBanHang_XemSanPham_tbx_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jNhanVienBanHang_XemSanPham_lb_AnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JNhanVienBanHang_XemSanPham_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(JNhanVienBanHang_btn_ThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JNhanVienBanHang_btn_SuaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JNhanVienBanHang_btn_XoaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JNhanVienBanHang_btn_XemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_TinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_XemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_XemThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JNhanVienBanHang_btn_XemThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_SuaThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNhanVienBanHang_btn_ThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_SuaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XoaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_TinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_SuaThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_XemSanPham_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JNhanVienBanHang_XemSanPham_panel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNhanVienBanHang_btn_XemHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_XemHoaDonMouseClicked

        JNhanVienBanHang_XemSanPham_panel.setVisible(true);
    }//GEN-LAST:event_JNhanVienBanHang_btn_XemHoaDonMouseClicked

    private void JNhanVienBanHang_btn_XemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_XemHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_btn_XemHoaDonActionPerformed

    private void JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked
        JNhanVienBanHang_XemSanPham_panel.setVisible(false);

    }//GEN-LAST:event_JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked

    private void jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed

    private void jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed

    private void JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JNhanVienBanHang_XemSanPham_btn_TimKiem;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_DonGia;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_LoaiSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_MaSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_SoLuong;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_TenSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_TimKiem;
    private javax.swing.JPanel JNhanVienBanHang_XemSanPham_panel;
    private javax.swing.JTable JNhanVienBanHang_XemSanPham_tb_BangSanPham;
    private javax.swing.JButton JNhanVienBanHang_btn_InHoaDon;
    private javax.swing.JButton JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab;
    private javax.swing.JButton JNhanVienBanHang_btn_SuaKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_SuaThongTinCaNhan;
    private javax.swing.JButton JNhanVienBanHang_btn_ThanhToan;
    private javax.swing.JButton JNhanVienBanHang_btn_ThemKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_TinhTien;
    private javax.swing.JButton JNhanVienBanHang_btn_XemHoaDon;
    private javax.swing.JButton JNhanVienBanHang_btn_XemKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_XemKho;
    private javax.swing.JButton JNhanVienBanHang_btn_XemThongTinCaNhan;
    private javax.swing.JButton JNhanVienBanHang_btn_XemThongTinSP;
    private javax.swing.JButton JNhanVienBanHang_btn_XoaKhachHang;
    private javax.swing.JButton jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang;
    private javax.swing.JLabel jNhanVienBanHang_XemSanPham_lb_AnhSanPham;
    private javax.swing.JScrollPane jNhanVienBanHang_XemSanPham_sp_TimKiem;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_DonGia;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_MaSanPham;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_SoLuong;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_TenSanPham;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_TimKiem;
    // End of variables declaration//GEN-END:variables
}
