/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVienBanHang;

/**
 *
 * @author MAIHUUTUAN
 */
public class JNhanVienBanHang extends javax.swing.JFrame {

    /**
     * Creates new form JNhanVienBanHang
     */
    public JNhanVienBanHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JNhanVienBanHang_btn_ThoatChuongTrinh = new javax.swing.JButton();
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab = new javax.swing.JButton();
        JNhanVienBanHang_btn_SuaThongTinCaNhan = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemThongTinCaNhan = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemThongTinSP = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemKho = new javax.swing.JButton();
        JNhanVienBanHang_btn_TinhTien = new javax.swing.JButton();
        JNhanVienBanHang_btn_ThanhToan = new javax.swing.JButton();
        JNhanVienBanHang_btn_InHoaDon = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemHoaDon = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_XoaKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_SuaKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_ThemKhachHang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JNhanVienBanHang_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 1000));

        JNhanVienBanHang_btn_ThoatChuongTrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit copy.png"))); // NOI18N

        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigate_cross copy.png"))); // NOI18N

        JNhanVienBanHang_btn_SuaThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/security_agent_edit copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer-service-icon copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemThongTinSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-good copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kho copy.png"))); // NOI18N

        JNhanVienBanHang_btn_TinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/scan copy.png"))); // NOI18N

        JNhanVienBanHang_btn_ThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Payments_payment_card_credit copy.png"))); // NOI18N

        JNhanVienBanHang_btn_InHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/receipt_printer copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XemHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/View_ebills_Icon copy.png"))); // NOI18N
        JNhanVienBanHang_btn_XemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_btn_XemHoaDonActionPerformed(evt);
            }
        });

        JNhanVienBanHang_btn_XemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_view copy.png"))); // NOI18N

        JNhanVienBanHang_btn_XoaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_delete copy.png"))); // NOI18N

        JNhanVienBanHang_btn_SuaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_edit copy.png"))); // NOI18N

        JNhanVienBanHang_btn_ThemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_add copy.png"))); // NOI18N

        JNhanVienBanHang_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/husky-clipart-akita-18.png"))); // NOI18N
        JNhanVienBanHang_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JNhanVienBanHang_btn_ThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JNhanVienBanHang_btn_SuaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JNhanVienBanHang_btn_XoaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JNhanVienBanHang_btn_XemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(JNhanVienBanHang_btn_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JNhanVienBanHang_btn_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(JNhanVienBanHang_btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(JNhanVienBanHang_btn_TinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(JNhanVienBanHang_btn_XemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(JNhanVienBanHang_btn_XemThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JNhanVienBanHang_btn_XemThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(JNhanVienBanHang_btn_SuaThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(JNhanVienBanHang_btn_ThoatChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNhanVienBanHang_logo)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNhanVienBanHang_btn_ThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_SuaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XoaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_TinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_XemThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_SuaThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNhanVienBanHang_btn_ThoatChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNhanVienBanHang_logo)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        JNhanVienBanHang_logo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNhanVienBanHang_btn_XemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_XemHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_btn_XemHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JNhanVienBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JNhanVienBanHang_btn_InHoaDon;
    private javax.swing.JButton JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab;
    private javax.swing.JButton JNhanVienBanHang_btn_SuaKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_SuaThongTinCaNhan;
    private javax.swing.JButton JNhanVienBanHang_btn_ThanhToan;
    private javax.swing.JButton JNhanVienBanHang_btn_ThemKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_ThoatChuongTrinh;
    private javax.swing.JButton JNhanVienBanHang_btn_TinhTien;
    private javax.swing.JButton JNhanVienBanHang_btn_XemHoaDon;
    private javax.swing.JButton JNhanVienBanHang_btn_XemKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_XemKho;
    private javax.swing.JButton JNhanVienBanHang_btn_XemThongTinCaNhan;
    private javax.swing.JButton JNhanVienBanHang_btn_XemThongTinSP;
    private javax.swing.JButton JNhanVienBanHang_btn_XoaKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_logo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
