/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVienBanHang;

import java.util.Calendar;

/**
 *
 * @author MAIHUUTUAN
 */
public class JNhanVienBanHang extends javax.swing.JFrame {

    /**
     * Creates new form JNhanVienBanHang
     */
    public JNhanVienBanHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JNhanVienBanHang_XemSanPham_panel = new javax.swing.JPanel();
        JNhanVienBanHang_XemSanPham_lb_TimKiem = new javax.swing.JLabel();
        jNhanVienBanHang_XemSanPham_tbx_TimKiem = new javax.swing.JTextField();
        JNhanVienBanHang_XemSanPham_btn_TimKiem = new javax.swing.JButton();
        jNhanVienBanHang_XemSanPham_sp_TimKiem = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemSanPham_tb_BangSanPham = new javax.swing.JTable();
        JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham = new javax.swing.JLabel();
        jNhanVienBanHang_XemSanPham_lb_AnhSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_MaSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_LoaiSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_TenSanPham = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_DonGia = new javax.swing.JLabel();
        JNhanVienBanHang_XemSanPham_lb_SoLuong = new javax.swing.JLabel();
        jNhanVienBanHang_XemSanPham_tbx_MaSanPham = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_TenSanPham = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_DonGia = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_tbx_SoLuong = new javax.swing.JTextField();
        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang = new javax.swing.JButton();
        JNhanVienBanHang_XemHoaDon_panel = new javax.swing.JPanel();
        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_time_Time = new com.toedter.calendar.JDateChooser();
        JNhanVienBanHang_XemHoaDon_btn_TimKiem = new javax.swing.JButton();
        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon = new javax.swing.JTable();
        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon = new javax.swing.JLabel();
        JNhanVienBanHang_XemHoaDon_lb_Tong = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        JNhanVienBanHang_logo = new javax.swing.JLabel();
        JNhanVienBanHang_btn_ThemKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_SuaKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_XoaKhachHang = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemHoaDon = new javax.swing.JButton();
        JNhanVienBanHang_btn_InHoaDon = new javax.swing.JButton();
        JNhanVienBanHang_btn_ThanhToan = new javax.swing.JButton();
        JNhanVienBanHang_btn_TinhTien = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemKho = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemThongTinSP = new javax.swing.JButton();
        JNhanVienBanHang_btn_XemThongTinCaNhan = new javax.swing.JButton();
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab = new javax.swing.JButton();
        JNhanVienBanHang_btn_ThoatChuongTrinh = new javax.swing.JButton();
        JNhanVienBanHang_btn_SuaThongTinCaNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        JNhanVienBanHang_XemSanPham_panel.setPreferredSize(new java.awt.Dimension(1366, 600));
        JNhanVienBanHang_XemSanPham_panel.setLayout(null);

        JNhanVienBanHang_XemSanPham_lb_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_TimKiem.setText("TÌM KIẾM SẢN PHẨM");
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_lb_TimKiem);
        JNhanVienBanHang_XemSanPham_lb_TimKiem.setBounds(20, 0, 390, 50);

        jNhanVienBanHang_XemSanPham_tbx_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_tbx_TimKiem);
        jNhanVienBanHang_XemSanPham_tbx_TimKiem.setBounds(20, 90, 351, 40);

        JNhanVienBanHang_XemSanPham_btn_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_btn_TimKiem.setText("Tìm kiếm");
        JNhanVienBanHang_XemSanPham_btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_btn_TimKiem);
        JNhanVienBanHang_XemSanPham_btn_TimKiem.setBounds(400, 90, 120, 40);

        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Loại sản phẩm", "Tên sản phẩm", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemSanPham_tb_BangSanPham.setRowHeight(20);
        jNhanVienBanHang_XemSanPham_sp_TimKiem.setViewportView(JNhanVienBanHang_XemSanPham_tb_BangSanPham);

        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_sp_TimKiem);
        jNhanVienBanHang_XemSanPham_sp_TimKiem.setBounds(18, 166, 529, 406);

        JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham.setText("Thông tin sản phẩm");
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham);
        JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham.setBounds(856, 61, 250, 29);

        jNhanVienBanHang_XemSanPham_lb_AnhSanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNhanVienBanHang_XemSanPham_lb_AnhSanPham.setText("    Ảnh sản phẩm");
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_lb_AnhSanPham);
        jNhanVienBanHang_XemSanPham_lb_AnhSanPham.setBounds(577, 130, 170, 198);

        JNhanVienBanHang_XemSanPham_lb_MaSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_MaSanPham.setText("Mã sản phẩm:");
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_lb_MaSanPham);
        JNhanVienBanHang_XemSanPham_lb_MaSanPham.setBounds(779, 138, 170, 25);

        JNhanVienBanHang_XemSanPham_lb_LoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_LoaiSanPham.setText("Loại sản phẩm:");
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_lb_LoaiSanPham);
        JNhanVienBanHang_XemSanPham_lb_LoaiSanPham.setBounds(779, 193, 170, 25);

        JNhanVienBanHang_XemSanPham_lb_TenSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_TenSanPham.setText("Tên sản phẩm:");
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_lb_TenSanPham);
        JNhanVienBanHang_XemSanPham_lb_TenSanPham.setBounds(779, 250, 170, 25);

        JNhanVienBanHang_XemSanPham_lb_DonGia.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_DonGia.setText("Đơn giá:");
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_lb_DonGia);
        JNhanVienBanHang_XemSanPham_lb_DonGia.setBounds(779, 300, 170, 25);

        JNhanVienBanHang_XemSanPham_lb_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemSanPham_lb_SoLuong.setText("Số lượng:");
        JNhanVienBanHang_XemSanPham_panel.add(JNhanVienBanHang_XemSanPham_lb_SoLuong);
        JNhanVienBanHang_XemSanPham_lb_SoLuong.setBounds(779, 353, 170, 25);

        jNhanVienBanHang_XemSanPham_tbx_MaSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_MaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_tbx_MaSanPham);
        jNhanVienBanHang_XemSanPham_tbx_MaSanPham.setBounds(954, 135, 208, 31);

        jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham);
        jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham.setBounds(954, 190, 208, 31);

        jNhanVienBanHang_XemSanPham_tbx_TenSanPham.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_TenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_tbx_TenSanPham);
        jNhanVienBanHang_XemSanPham_tbx_TenSanPham.setBounds(954, 247, 370, 31);

        jNhanVienBanHang_XemSanPham_tbx_DonGia.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_DonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_tbx_DonGia);
        jNhanVienBanHang_XemSanPham_tbx_DonGia.setBounds(954, 297, 208, 31);

        jNhanVienBanHang_XemSanPham_tbx_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_tbx_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_tbx_SoLuong);
        jNhanVienBanHang_XemSanPham_tbx_SoLuong.setBounds(954, 350, 208, 31);

        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang.setText("Thêm vào giỏ hàng");
        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemSanPham_panel.add(jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang);
        jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang.setBounds(835, 436, 288, 54);

        getContentPane().add(JNhanVienBanHang_XemSanPham_panel);
        JNhanVienBanHang_XemSanPham_panel.setBounds(0, 110, 1366, 600);
        JNhanVienBanHang_XemSanPham_panel.setVisible(false);

        JNhanVienBanHang_XemHoaDon_panel.setLayout(null);

        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon.setText("TRA CỨU HÓA ĐƠN");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_XemHoaDon);
        JNhanVienBanHang_XemHoaDon_lb_XemHoaDon.setBounds(0, 0, 390, 50);

        JNhanVienBanHang_XemHoaDon_time_Time.setDateFormatString("d MMMM, yyyy");
        JNhanVienBanHang_XemHoaDon_time_Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_time_Time);
        JNhanVienBanHang_XemHoaDon_time_Time.setBounds(0, 80, 250, 30);

        JNhanVienBanHang_XemHoaDon_btn_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_btn_TimKiem.setText("Tìm kiếm");
        JNhanVienBanHang_XemHoaDon_btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_btn_TimKiem);
        JNhanVienBanHang_XemHoaDon_btn_TimKiem.setBounds(260, 80, 120, 30);

        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon.setText("Bảng Hóa Đơn");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_BangHoaDon);
        JNhanVienBanHang_XemHoaDon_lb_BangHoaDon.setBounds(180, 160, 160, 29);

        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Người lập hóa đơn", "Ngày lập hóa đơn", "Khách hàng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setRowHeight(20);
        jScrollPane3.setViewportView(JNhanVienBanHang_XemHoaDon_tb_BangHoaDon);
        //JNhanVienBanHang_XemHoaDon_tb_BangHoaDon.setVisible(false);

        JNhanVienBanHang_XemHoaDon_panel.add(jScrollPane3);
        jScrollPane3.setBounds(0, 210, 520, 330);

        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Loại sản phẩm", "Tên sản phẩm", "Giá", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setMinimumSize(new java.awt.Dimension(60, 480));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setPreferredSize(new java.awt.Dimension(300, 480));
        JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon.setRowHeight(20);
        jScrollPane1.setViewportView(JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon);

        JNhanVienBanHang_XemHoaDon_panel.add(jScrollPane1);
        jScrollPane1.setBounds(600, 210, 650, 330);
        jScrollPane1.getAccessibleContext().setAccessibleName("");

        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien.setText("...................................");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien);
        JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien.setBounds(770, 80, 390, 25);

        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien.setText("Tên nhân viên:");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_TenNhanVien);
        JNhanVienBanHang_XemHoaDon_lb_TenNhanVien.setBounds(600, 80, 170, 25);

        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang.setText("Tên khách hàng:");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_TenKhachHang);
        JNhanVienBanHang_XemHoaDon_lb_TenKhachHang.setBounds(600, 120, 170, 25);

        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang.setText("...................................");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang);
        JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang.setBounds(770, 120, 380, 25);

        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon.setText("Bảng Chi Tiết Hóa Đơn");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon);
        JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon.setBounds(790, 160, 250, 29);

        JNhanVienBanHang_XemHoaDon_lb_Tong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        JNhanVienBanHang_XemHoaDon_lb_Tong.setText("Tổng:");
        JNhanVienBanHang_XemHoaDon_panel.add(JNhanVienBanHang_XemHoaDon_lb_Tong);
        JNhanVienBanHang_XemHoaDon_lb_Tong.setBounds(980, 560, 60, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        JNhanVienBanHang_XemHoaDon_panel.add(jTextField1);
        jTextField1.setBounds(1070, 560, 180, 31);

        getContentPane().add(JNhanVienBanHang_XemHoaDon_panel);
        JNhanVienBanHang_XemHoaDon_panel.setBounds(50, 110, 1310, 610);
        JNhanVienBanHang_XemHoaDon_panel.setVisible(false);

        JNhanVienBanHang_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/husky-clipart-akita-18.png"))); // NOI18N
        JNhanVienBanHang_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(JNhanVienBanHang_logo);
        JNhanVienBanHang_logo.setBounds(480, 200, 400, 400);
        JNhanVienBanHang_logo.getAccessibleContext().setAccessibleDescription("");
        //JNhanVienBanHang_logo.setVisible(false);

        JNhanVienBanHang_btn_ThemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_add copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_ThemKhachHang);
        JNhanVienBanHang_btn_ThemKhachHang.setBounds(0, 0, 90, 90);
        JNhanVienBanHang_btn_ThemKhachHang.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_SuaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_edit copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_SuaKhachHang);
        JNhanVienBanHang_btn_SuaKhachHang.setBounds(90, 0, 90, 90);
        JNhanVienBanHang_btn_SuaKhachHang.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_XemKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_view copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_XemKhachHang);
        JNhanVienBanHang_btn_XemKhachHang.setBounds(270, 0, 90, 90);
        JNhanVienBanHang_btn_XemKhachHang.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_XoaKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/businessman_delete copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_XoaKhachHang);
        JNhanVienBanHang_btn_XoaKhachHang.setBounds(180, 0, 90, 90);
        JNhanVienBanHang_btn_XoaKhachHang.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_XemHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/View_ebills_Icon copy.png"))); // NOI18N
        JNhanVienBanHang_btn_XemHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JNhanVienBanHang_btn_XemHoaDonMouseClicked(evt);
            }
        });
        JNhanVienBanHang_btn_XemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_btn_XemHoaDonActionPerformed(evt);
            }
        });
        getContentPane().add(JNhanVienBanHang_btn_XemHoaDon);
        JNhanVienBanHang_btn_XemHoaDon.setBounds(360, 0, 90, 90);
        JNhanVienBanHang_btn_XemHoaDon.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_InHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/receipt_printer copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_InHoaDon);
        JNhanVienBanHang_btn_InHoaDon.setBounds(450, 0, 90, 90);
        JNhanVienBanHang_btn_InHoaDon.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_ThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Payments_payment_card_credit copy.png"))); // NOI18N
        JNhanVienBanHang_btn_ThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JNhanVienBanHang_btn_ThanhToanMouseClicked(evt);
            }
        });
        JNhanVienBanHang_btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_btn_ThanhToanActionPerformed(evt);
            }
        });
        getContentPane().add(JNhanVienBanHang_btn_ThanhToan);
        JNhanVienBanHang_btn_ThanhToan.setBounds(540, 0, 90, 90);

        JNhanVienBanHang_btn_TinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/scan copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_TinhTien);
        JNhanVienBanHang_btn_TinhTien.setBounds(630, 0, 90, 90);
        JNhanVienBanHang_btn_TinhTien.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_XemKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kho copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_XemKho);
        JNhanVienBanHang_btn_XemKho.setBounds(720, 0, 90, 90);
        JNhanVienBanHang_btn_XemKho.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_XemThongTinSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-good copy.png"))); // NOI18N
        JNhanVienBanHang_btn_XemThongTinSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JNhanVienBanHang_btn_XemThongTinSPMouseClicked(evt);
            }
        });
        getContentPane().add(JNhanVienBanHang_btn_XemThongTinSP);
        JNhanVienBanHang_btn_XemThongTinSP.setBounds(810, 0, 90, 90);
        JNhanVienBanHang_btn_XemThongTinSP.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_XemThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer-service-icon copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_XemThongTinCaNhan);
        JNhanVienBanHang_btn_XemThongTinCaNhan.setBounds(990, 0, 90, 90);
        JNhanVienBanHang_btn_XemThongTinCaNhan.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigate_cross copy.png"))); // NOI18N
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked(evt);
            }
        });
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabActionPerformed(evt);
            }
        });
        getContentPane().add(JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab);
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.setBounds(1170, 0, 90, 90);
        JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_ThoatChuongTrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit copy.png"))); // NOI18N
        JNhanVienBanHang_btn_ThoatChuongTrinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNhanVienBanHang_btn_ThoatChuongTrinhActionPerformed(evt);
            }
        });
        getContentPane().add(JNhanVienBanHang_btn_ThoatChuongTrinh);
        JNhanVienBanHang_btn_ThoatChuongTrinh.setBounds(1260, 0, 90, 90);
        JNhanVienBanHang_btn_ThoatChuongTrinh.getAccessibleContext().setAccessibleParent(this);

        JNhanVienBanHang_btn_SuaThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/security_agent_edit copy.png"))); // NOI18N
        getContentPane().add(JNhanVienBanHang_btn_SuaThongTinCaNhan);
        JNhanVienBanHang_btn_SuaThongTinCaNhan.setBounds(1080, 0, 90, 90);
        JNhanVienBanHang_btn_SuaThongTinCaNhan.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNhanVienBanHang_btn_XemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_XemHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_btn_XemHoaDonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void JNhanVienBanHang_btn_XemHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_XemHoaDonMouseClicked
        JNhanVienBanHang_XemSanPham_panel.setVisible(false);
        JNhanVienBanHang_XemHoaDon_panel.setVisible(true);
    }//GEN-LAST:event_JNhanVienBanHang_btn_XemHoaDonMouseClicked

    
    private void JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked
        JNhanVienBanHang_XemHoaDon_panel.setVisible(false);
        JNhanVienBanHang_XemSanPham_panel.setVisible(false);
    }//GEN-LAST:event_JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabMouseClicked
    
    private void JNhanVienBanHang_btn_ThoatChuongTrinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_ThoatChuongTrinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_btn_ThoatChuongTrinhActionPerformed

    private void JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTabActionPerformed

    private void JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemHoaDon_btn_TimKiemActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_TimKiemActionPerformed

    private void JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_XemSanPham_btn_TimKiemActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_MaSanPhamActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_LoaiSanPhamActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_DonGiaActionPerformed

    private void jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_SoLuongActionPerformed

    private void jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHangActionPerformed

    private void JNhanVienBanHang_btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNhanVienBanHang_btn_ThanhToanActionPerformed

    private void JNhanVienBanHang_btn_ThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_ThanhToanMouseClicked
        
    }//GEN-LAST:event_JNhanVienBanHang_btn_ThanhToanMouseClicked

    private void jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNhanVienBanHang_XemSanPham_tbx_TenSanPhamActionPerformed

    private void JNhanVienBanHang_btn_XemThongTinSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JNhanVienBanHang_btn_XemThongTinSPMouseClicked
        JNhanVienBanHang_XemHoaDon_panel.setVisible(false);
        JNhanVienBanHang_XemSanPham_panel.setVisible(true);
    }//GEN-LAST:event_JNhanVienBanHang_btn_XemThongTinSPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JNhanVienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JNhanVienBanHang().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JNhanVienBanHang_XemHoaDon_btn_TimKiem;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_BangChiTietHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_BangHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_TenKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_TenNhanVien;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_Tong;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_XemHoaDon;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_kqTenKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_XemHoaDon_lb_kqTenNhanVien;
    private javax.swing.JPanel JNhanVienBanHang_XemHoaDon_panel;
    private javax.swing.JTable JNhanVienBanHang_XemHoaDon_tb_BangChiTietHoaDon;
    private javax.swing.JTable JNhanVienBanHang_XemHoaDon_tb_BangHoaDon;
    private com.toedter.calendar.JDateChooser JNhanVienBanHang_XemHoaDon_time_Time;
    private javax.swing.JButton JNhanVienBanHang_XemSanPham_btn_TimKiem;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_DonGia;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_LoaiSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_MaSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_SoLuong;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_TenSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_ThongTinSanPham;
    private javax.swing.JLabel JNhanVienBanHang_XemSanPham_lb_TimKiem;
    private javax.swing.JPanel JNhanVienBanHang_XemSanPham_panel;
    private javax.swing.JTable JNhanVienBanHang_XemSanPham_tb_BangSanPham;
    private javax.swing.JButton JNhanVienBanHang_btn_InHoaDon;
    private javax.swing.JButton JNhanVienBanHang_btn_JNhanVienBanHang_btn_DongTab;
    private javax.swing.JButton JNhanVienBanHang_btn_SuaKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_SuaThongTinCaNhan;
    private javax.swing.JButton JNhanVienBanHang_btn_ThanhToan;
    private javax.swing.JButton JNhanVienBanHang_btn_ThemKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_ThoatChuongTrinh;
    private javax.swing.JButton JNhanVienBanHang_btn_TinhTien;
    private javax.swing.JButton JNhanVienBanHang_btn_XemHoaDon;
    private javax.swing.JButton JNhanVienBanHang_btn_XemKhachHang;
    private javax.swing.JButton JNhanVienBanHang_btn_XemKho;
    private javax.swing.JButton JNhanVienBanHang_btn_XemThongTinCaNhan;
    private javax.swing.JButton JNhanVienBanHang_btn_XemThongTinSP;
    private javax.swing.JButton JNhanVienBanHang_btn_XoaKhachHang;
    private javax.swing.JLabel JNhanVienBanHang_logo;
    private javax.swing.JButton jNhanVienBanHang_XemSanPham_btn_ThemVaoGioHang;
    private javax.swing.JLabel jNhanVienBanHang_XemSanPham_lb_AnhSanPham;
    private javax.swing.JScrollPane jNhanVienBanHang_XemSanPham_sp_TimKiem;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_DonGia;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_LoaiSanPham;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_MaSanPham;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_SoLuong;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_TenSanPham;
    private javax.swing.JTextField jNhanVienBanHang_XemSanPham_tbx_TimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
